/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Task Management
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ArrayInner
 */
export interface ArrayInner {
}
/**
 * 
 * @export
 * @interface Errormessagedto
 */
export interface Errormessagedto {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof Errormessagedto
     */
    'locale'?: string | null;
    /**
     * 
     * @type {Localeorigin}
     * @memberof Errormessagedto
     */
    'localeOrigin'?: Localeorigin | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof Errormessagedto
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface Errorresponsedto
 */
export interface Errorresponsedto {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof Errorresponsedto
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof Errorresponsedto
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<Errormessagedto>}
     * @memberof Errorresponsedto
     */
    'messages'?: Array<Errormessagedto>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<Errormessagedto>}
     * @memberof Errorresponsedto
     */
    'causes'?: Array<Errormessagedto>;
}
/**
 * 
 * @export
 * @interface GetTaskStatusV1401Response
 */
export interface GetTaskStatusV1401Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetTaskStatusV1401Response
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface GetTaskStatusV1429Response
 */
export interface GetTaskStatusV1429Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetTaskStatusV1429Response
     */
    'message'?: any;
}
/**
 * A JSONPatch Operation as defined by [RFC 6902 - JSON Patch](https://tools.ietf.org/html/rfc6902)
 * @export
 * @interface Jsonpatchoperation
 */
export interface Jsonpatchoperation {
    /**
     * The operation to be performed
     * @type {string}
     * @memberof Jsonpatchoperation
     */
    'op': JsonpatchoperationOpEnum;
    /**
     * A string JSON Pointer representing the target path to an element to be affected by the operation
     * @type {string}
     * @memberof Jsonpatchoperation
     */
    'path': string;
    /**
     * 
     * @type {JsonpatchoperationValue}
     * @memberof Jsonpatchoperation
     */
    'value'?: JsonpatchoperationValue;
}

export const JsonpatchoperationOpEnum = {
    Add: 'add',
    Remove: 'remove',
    Replace: 'replace',
    Move: 'move',
    Copy: 'copy',
    Test: 'test'
} as const;

export type JsonpatchoperationOpEnum = typeof JsonpatchoperationOpEnum[keyof typeof JsonpatchoperationOpEnum];

/**
 * @type JsonpatchoperationValue
 * The value to be used for the operation, required for \"add\" and \"replace\" operations
 * @export
 */
export type JsonpatchoperationValue = Array<ArrayInner> | boolean | number | object | string;

/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const Localeorigin = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type Localeorigin = typeof Localeorigin[keyof typeof Localeorigin];


/**
 * Localized error message to indicate a failed invocation or error if any.
 * @export
 * @interface Localizedmessage
 */
export interface Localizedmessage {
    /**
     * Message locale
     * @type {string}
     * @memberof Localizedmessage
     */
    'locale': string;
    /**
     * Message text
     * @type {string}
     * @memberof Localizedmessage
     */
    'message': string;
}
/**
 * 
 * @export
 * @interface Target
 */
export interface Target {
    /**
     * Target ID
     * @type {string}
     * @memberof Target
     */
    'id'?: string;
    /**
     * Target type
     * @type {string}
     * @memberof Target
     */
    'type'?: TargetTypeEnum | null;
    /**
     * Target name
     * @type {string}
     * @memberof Target
     */
    'name'?: string;
}

export const TargetTypeEnum = {
    Application: 'APPLICATION',
    Identity: 'IDENTITY'
} as const;

export type TargetTypeEnum = typeof TargetTypeEnum[keyof typeof TargetTypeEnum];

/**
 * Definition of a type of task, used to invoke tasks
 * @export
 * @interface Taskdefinitionsummary
 */
export interface Taskdefinitionsummary {
    /**
     * System-generated unique ID of the TaskDefinition
     * @type {string}
     * @memberof Taskdefinitionsummary
     */
    'id': string;
    /**
     * Name of the TaskDefinition
     * @type {string}
     * @memberof Taskdefinitionsummary
     */
    'uniqueName': string;
    /**
     * Description of the TaskDefinition
     * @type {string}
     * @memberof Taskdefinitionsummary
     */
    'description': string | null;
    /**
     * Name of the parent of the TaskDefinition
     * @type {string}
     * @memberof Taskdefinitionsummary
     */
    'parentName': string;
    /**
     * Executor of the TaskDefinition
     * @type {string}
     * @memberof Taskdefinitionsummary
     */
    'executor': string | null;
    /**
     * Formal parameters of the TaskDefinition, without values
     * @type {{ [key: string]: any; }}
     * @memberof Taskdefinitionsummary
     */
    'arguments': { [key: string]: any; };
}
/**
 * Task return details
 * @export
 * @interface Taskreturndetails
 */
export interface Taskreturndetails {
    /**
     * Display name of the TaskReturnDetails
     * @type {string}
     * @memberof Taskreturndetails
     */
    'name': string;
    /**
     * Attribute the TaskReturnDetails is for
     * @type {string}
     * @memberof Taskreturndetails
     */
    'attributeName': string;
}
/**
 * Details and current status of a specific task
 * @export
 * @interface Taskstatus
 */
export interface Taskstatus {
    /**
     * System-generated unique ID of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'id': string;
    /**
     * Type of task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'type': TaskstatusTypeEnum;
    /**
     * Name of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'uniqueName': string;
    /**
     * Description of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'description': string;
    /**
     * Name of the parent of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'parentName': string | null;
    /**
     * Service to execute the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'launcher': string;
    /**
     * 
     * @type {Target}
     * @memberof Taskstatus
     */
    'target'?: Target | null;
    /**
     * Creation date of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'created': string;
    /**
     * Last modification date of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'modified': string | null;
    /**
     * Launch date of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'launched': string | null;
    /**
     * Completion date of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'completed': string | null;
    /**
     * Completion status of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'completionStatus': TaskstatusCompletionStatusEnum | null;
    /**
     * Messages associated with the task this TaskStatus represents
     * @type {Array<Taskstatusmessage>}
     * @memberof Taskstatus
     */
    'messages': Array<Taskstatusmessage>;
    /**
     * Return values from the task this TaskStatus represents
     * @type {Array<Taskreturndetails>}
     * @memberof Taskstatus
     */
    'returns': Array<Taskreturndetails>;
    /**
     * Attributes of the task this TaskStatus represents
     * @type {{ [key: string]: any; }}
     * @memberof Taskstatus
     */
    'attributes': { [key: string]: any; };
    /**
     * Current progress of the task this TaskStatus represents
     * @type {string}
     * @memberof Taskstatus
     */
    'progress': string | null;
    /**
     * Current percentage completion of the task this TaskStatus represents
     * @type {number}
     * @memberof Taskstatus
     */
    'percentComplete': number;
    /**
     * 
     * @type {Taskdefinitionsummary}
     * @memberof Taskstatus
     */
    'taskDefinitionSummary'?: Taskdefinitionsummary;
}

export const TaskstatusTypeEnum = {
    Quartz: 'QUARTZ',
    Qpoc: 'QPOC',
    QueuedTask: 'QUEUED_TASK'
} as const;

export type TaskstatusTypeEnum = typeof TaskstatusTypeEnum[keyof typeof TaskstatusTypeEnum];
export const TaskstatusCompletionStatusEnum = {
    Success: 'SUCCESS',
    Warning: 'WARNING',
    Error: 'ERROR',
    Terminated: 'TERMINATED',
    Temperror: 'TEMPERROR'
} as const;

export type TaskstatusCompletionStatusEnum = typeof TaskstatusCompletionStatusEnum[keyof typeof TaskstatusCompletionStatusEnum];

/**
 * TaskStatus Message
 * @export
 * @interface Taskstatusmessage
 */
export interface Taskstatusmessage {
    /**
     * Type of the message
     * @type {string}
     * @memberof Taskstatusmessage
     */
    'type': TaskstatusmessageTypeEnum;
    /**
     * 
     * @type {Localizedmessage}
     * @memberof Taskstatusmessage
     */
    'localizedText': Localizedmessage | null;
    /**
     * Key of the message
     * @type {string}
     * @memberof Taskstatusmessage
     */
    'key': string;
    /**
     * Message parameters for internationalization
     * @type {Array<TaskstatusmessageParametersInner>}
     * @memberof Taskstatusmessage
     */
    'parameters': Array<TaskstatusmessageParametersInner> | null;
}

export const TaskstatusmessageTypeEnum = {
    Info: 'INFO',
    Warn: 'WARN',
    Error: 'ERROR'
} as const;

export type TaskstatusmessageTypeEnum = typeof TaskstatusmessageTypeEnum[keyof typeof TaskstatusmessageTypeEnum];

/**
 * 
 * @export
 * @interface TaskstatusmessageParametersInner
 */
export interface TaskstatusmessageParametersInner {
}

/**
 * TaskManagementApi - axios parameter creator
 * @export
 */
export const TaskManagementApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this endpoint to get a list of statuses for **all** tasks, including completed, in-progress, terminated, and errored tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks. Data for tasks older than 90 days will not be returned. For a list of **in-progress** tasks, apply the isnull filter to the Completion Status field. 
         * @summary Retrieve task status list
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {string} [filters] Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **id**: *eq, in*  **sourceId**: *eq, in*  **completionStatus**: *eq, in, isnull*  **type**: *eq, in*  **launcher**: *eq, in*  **Possible Values:** CLOUD_ACCOUNT_AGGREGATION, CLOUD_GROUP_AGGREGATION, CLOUD_PROCESS_UNCORRELATED_ACCOUNTS, CLOUD_REFRESH_ROLE, SOURCE_APPLICATION_DISCOVERY, AI_AGENT_AGGREGATION, CLOUD_ENTITLEMENT_IMPORT, CLOUD_UNCORRELATED_REFRESH, CLOUD_IDENTITY_AGGREGATION, CLOUD_ATTRIBUTE_SYNCHRONIZATION, IDENTITY_REFRESH, APPLICATION_DISCOVERY, MACHINE_IDENTITY_AGGREGATION, MACHINE_IDENTITY_DELETION, ACCOUNT_DELETION
         * @param {string} [sorters] Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)  Sorting is supported for the following fields: **created**
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTaskStatusListV1: async (limit?: number, offset?: number, count?: boolean, filters?: string, sorters?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/task-status/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }

            if (sorters !== undefined) {
                localVarQueryParameter['sorters'] = sorters;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Get task status by task ID. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
         * @summary Get task status by id
         * @param {string} id Task ID.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTaskStatusV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTaskStatusV1', 'id', id)
            const localVarPath = `/task-status/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Update a current task status by task ID. Use this API to clear a pending task by updating the completionStatus and completed attributes.
         * @summary Update task status by id
         * @param {string} id Task ID.
         * @param {Array<Jsonpatchoperation>} jsonpatchoperation The JSONPatch payload used to update the object.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskStatusV1: async (id: string, jsonpatchoperation: Array<Jsonpatchoperation>, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTaskStatusV1', 'id', id)
            // verify required parameter 'jsonpatchoperation' is not null or undefined
            assertParamExists('updateTaskStatusV1', 'jsonpatchoperation', jsonpatchoperation)
            const localVarPath = `/task-status/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(jsonpatchoperation, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaskManagementApi - functional programming interface
 * @export
 */
export const TaskManagementApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaskManagementApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this endpoint to get a list of statuses for **all** tasks, including completed, in-progress, terminated, and errored tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks. Data for tasks older than 90 days will not be returned. For a list of **in-progress** tasks, apply the isnull filter to the Completion Status field. 
         * @summary Retrieve task status list
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {string} [filters] Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **id**: *eq, in*  **sourceId**: *eq, in*  **completionStatus**: *eq, in, isnull*  **type**: *eq, in*  **launcher**: *eq, in*  **Possible Values:** CLOUD_ACCOUNT_AGGREGATION, CLOUD_GROUP_AGGREGATION, CLOUD_PROCESS_UNCORRELATED_ACCOUNTS, CLOUD_REFRESH_ROLE, SOURCE_APPLICATION_DISCOVERY, AI_AGENT_AGGREGATION, CLOUD_ENTITLEMENT_IMPORT, CLOUD_UNCORRELATED_REFRESH, CLOUD_IDENTITY_AGGREGATION, CLOUD_ATTRIBUTE_SYNCHRONIZATION, IDENTITY_REFRESH, APPLICATION_DISCOVERY, MACHINE_IDENTITY_AGGREGATION, MACHINE_IDENTITY_DELETION, ACCOUNT_DELETION
         * @param {string} [sorters] Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)  Sorting is supported for the following fields: **created**
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskStatusListV1(limit?: number, offset?: number, count?: boolean, filters?: string, sorters?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<Taskstatus>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskStatusListV1(limit, offset, count, filters, sorters, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskManagementApi.getTaskStatusListV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get task status by task ID. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
         * @summary Get task status by id
         * @param {string} id Task ID.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getTaskStatusV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Taskstatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTaskStatusV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskManagementApi.getTaskStatusV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update a current task status by task ID. Use this API to clear a pending task by updating the completionStatus and completed attributes.
         * @summary Update task status by id
         * @param {string} id Task ID.
         * @param {Array<Jsonpatchoperation>} jsonpatchoperation The JSONPatch payload used to update the object.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async updateTaskStatusV1(id: string, jsonpatchoperation: Array<Jsonpatchoperation>, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Taskstatus>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTaskStatusV1(id, jsonpatchoperation, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskManagementApi.updateTaskStatusV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TaskManagementApi - factory interface
 * @export
 */
export const TaskManagementApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaskManagementApiFp(configuration)
    return {
        /**
         * Use this endpoint to get a list of statuses for **all** tasks, including completed, in-progress, terminated, and errored tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks. Data for tasks older than 90 days will not be returned. For a list of **in-progress** tasks, apply the isnull filter to the Completion Status field. 
         * @summary Retrieve task status list
         * @param {TaskManagementApiGetTaskStatusListV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTaskStatusListV1(requestParameters: TaskManagementApiGetTaskStatusListV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<Taskstatus>> {
            return localVarFp.getTaskStatusListV1(requestParameters.limit, requestParameters.offset, requestParameters.count, requestParameters.filters, requestParameters.sorters, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Get task status by task ID. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
         * @summary Get task status by id
         * @param {TaskManagementApiGetTaskStatusV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTaskStatusV1(requestParameters: TaskManagementApiGetTaskStatusV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Taskstatus> {
            return localVarFp.getTaskStatusV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Update a current task status by task ID. Use this API to clear a pending task by updating the completionStatus and completed attributes.
         * @summary Update task status by id
         * @param {TaskManagementApiUpdateTaskStatusV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updateTaskStatusV1(requestParameters: TaskManagementApiUpdateTaskStatusV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Taskstatus> {
            return localVarFp.updateTaskStatusV1(requestParameters.id, requestParameters.jsonpatchoperation, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getTaskStatusListV1 operation in TaskManagementApi.
 * @export
 * @interface TaskManagementApiGetTaskStatusListV1Request
 */
export interface TaskManagementApiGetTaskStatusListV1Request {
    /**
     * Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof TaskManagementApiGetTaskStatusListV1
     */
    readonly limit?: number

    /**
     * Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof TaskManagementApiGetTaskStatusListV1
     */
    readonly offset?: number

    /**
     * If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {boolean}
     * @memberof TaskManagementApiGetTaskStatusListV1
     */
    readonly count?: boolean

    /**
     * Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **id**: *eq, in*  **sourceId**: *eq, in*  **completionStatus**: *eq, in, isnull*  **type**: *eq, in*  **launcher**: *eq, in*  **Possible Values:** CLOUD_ACCOUNT_AGGREGATION, CLOUD_GROUP_AGGREGATION, CLOUD_PROCESS_UNCORRELATED_ACCOUNTS, CLOUD_REFRESH_ROLE, SOURCE_APPLICATION_DISCOVERY, AI_AGENT_AGGREGATION, CLOUD_ENTITLEMENT_IMPORT, CLOUD_UNCORRELATED_REFRESH, CLOUD_IDENTITY_AGGREGATION, CLOUD_ATTRIBUTE_SYNCHRONIZATION, IDENTITY_REFRESH, APPLICATION_DISCOVERY, MACHINE_IDENTITY_AGGREGATION, MACHINE_IDENTITY_DELETION, ACCOUNT_DELETION
     * @type {string}
     * @memberof TaskManagementApiGetTaskStatusListV1
     */
    readonly filters?: string

    /**
     * Sort results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#sorting-results)  Sorting is supported for the following fields: **created**
     * @type {string}
     * @memberof TaskManagementApiGetTaskStatusListV1
     */
    readonly sorters?: string
}

/**
 * Request parameters for getTaskStatusV1 operation in TaskManagementApi.
 * @export
 * @interface TaskManagementApiGetTaskStatusV1Request
 */
export interface TaskManagementApiGetTaskStatusV1Request {
    /**
     * Task ID.
     * @type {string}
     * @memberof TaskManagementApiGetTaskStatusV1
     */
    readonly id: string
}

/**
 * Request parameters for updateTaskStatusV1 operation in TaskManagementApi.
 * @export
 * @interface TaskManagementApiUpdateTaskStatusV1Request
 */
export interface TaskManagementApiUpdateTaskStatusV1Request {
    /**
     * Task ID.
     * @type {string}
     * @memberof TaskManagementApiUpdateTaskStatusV1
     */
    readonly id: string

    /**
     * The JSONPatch payload used to update the object.
     * @type {Array<Jsonpatchoperation>}
     * @memberof TaskManagementApiUpdateTaskStatusV1
     */
    readonly jsonpatchoperation: Array<Jsonpatchoperation>
}

/**
 * TaskManagementApi - object-oriented interface
 * @export
 * @class TaskManagementApi
 * @extends {BaseAPI}
 */
export class TaskManagementApi extends BaseAPI {
    /**
     * Use this endpoint to get a list of statuses for **all** tasks, including completed, in-progress, terminated, and errored tasks. Types of tasks include account and entitlement aggregation and other general background processing tasks. Data for tasks older than 90 days will not be returned. For a list of **in-progress** tasks, apply the isnull filter to the Completion Status field. 
     * @summary Retrieve task status list
     * @param {TaskManagementApiGetTaskStatusListV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskManagementApi
     */
    public getTaskStatusListV1(requestParameters: TaskManagementApiGetTaskStatusListV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return TaskManagementApiFp(this.configuration).getTaskStatusListV1(requestParameters.limit, requestParameters.offset, requestParameters.count, requestParameters.filters, requestParameters.sorters, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get task status by task ID. Types of tasks include account and entitlement aggregation and other general background processing tasks.  Data for tasks older than 90 days will not be returned.
     * @summary Get task status by id
     * @param {TaskManagementApiGetTaskStatusV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskManagementApi
     */
    public getTaskStatusV1(requestParameters: TaskManagementApiGetTaskStatusV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TaskManagementApiFp(this.configuration).getTaskStatusV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update a current task status by task ID. Use this API to clear a pending task by updating the completionStatus and completed attributes.
     * @summary Update task status by id
     * @param {TaskManagementApiUpdateTaskStatusV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskManagementApi
     */
    public updateTaskStatusV1(requestParameters: TaskManagementApiUpdateTaskStatusV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TaskManagementApiFp(this.configuration).updateTaskStatusV1(requestParameters.id, requestParameters.jsonpatchoperation, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



