/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Segments
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrormessagedtoV1
 */
export interface ErrormessagedtoV1 {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleoriginV1}
     * @memberof ErrormessagedtoV1
     */
    'localeOrigin'?: LocaleoriginV1 | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorresponsedtoV1
 */
export interface ErrorresponsedtoV1 {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'messages'?: Array<ErrormessagedtoV1>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'causes'?: Array<ErrormessagedtoV1>;
}
/**
 * 
 * @export
 * @interface ExpressionChildrenInnerV1
 */
export interface ExpressionChildrenInnerV1 {
    /**
     * Operator for the expression
     * @type {string}
     * @memberof ExpressionChildrenInnerV1
     */
    'operator'?: ExpressionChildrenInnerV1OperatorV1;
    /**
     * Name for the attribute
     * @type {string}
     * @memberof ExpressionChildrenInnerV1
     */
    'attribute'?: string | null;
    /**
     * 
     * @type {ValueV1}
     * @memberof ExpressionChildrenInnerV1
     */
    'value'?: ValueV1 | null;
    /**
     * There cannot be anymore nested children. This will always be null.
     * @type {string}
     * @memberof ExpressionChildrenInnerV1
     */
    'children'?: string | null;
}

export const ExpressionChildrenInnerV1OperatorV1 = {
    And: 'AND',
    Equals: 'EQUALS'
} as const;

export type ExpressionChildrenInnerV1OperatorV1 = typeof ExpressionChildrenInnerV1OperatorV1[keyof typeof ExpressionChildrenInnerV1OperatorV1];

/**
 * 
 * @export
 * @interface ExpressionV1
 */
export interface ExpressionV1 {
    /**
     * Operator for the expression
     * @type {string}
     * @memberof ExpressionV1
     */
    'operator'?: ExpressionV1OperatorV1;
    /**
     * Name for the attribute
     * @type {string}
     * @memberof ExpressionV1
     */
    'attribute'?: string | null;
    /**
     * 
     * @type {ValueV1}
     * @memberof ExpressionV1
     */
    'value'?: ValueV1 | null;
    /**
     * List of expressions
     * @type {Array<ExpressionChildrenInnerV1>}
     * @memberof ExpressionV1
     */
    'children'?: Array<ExpressionChildrenInnerV1> | null;
}

export const ExpressionV1OperatorV1 = {
    And: 'AND',
    Equals: 'EQUALS'
} as const;

export type ExpressionV1OperatorV1 = typeof ExpressionV1OperatorV1[keyof typeof ExpressionV1OperatorV1];

/**
 * 
 * @export
 * @interface ListSegmentsV1401ResponseV1
 */
export interface ListSegmentsV1401ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListSegmentsV1401ResponseV1
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface ListSegmentsV1429ResponseV1
 */
export interface ListSegmentsV1429ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListSegmentsV1429ResponseV1
     */
    'message'?: any;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleoriginV1 = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleoriginV1 = typeof LocaleoriginV1[keyof typeof LocaleoriginV1];


/**
 * The owner of this object.
 * @export
 * @interface OwnerreferencesegmentsV1
 */
export interface OwnerreferencesegmentsV1 {
    /**
     * Owner type. This field must be either left null or set to \'IDENTITY\' on input, otherwise a 400 Bad Request error will result.
     * @type {string}
     * @memberof OwnerreferencesegmentsV1
     */
    'type'?: OwnerreferencesegmentsV1TypeV1;
    /**
     * Identity id
     * @type {string}
     * @memberof OwnerreferencesegmentsV1
     */
    'id'?: string;
    /**
     * Human-readable display name of the owner. It may be left null or omitted in a POST or PATCH. If set, it must match the current value of the owner\'s display name, otherwise a 400 Bad Request error will result.
     * @type {string}
     * @memberof OwnerreferencesegmentsV1
     */
    'name'?: string;
}

export const OwnerreferencesegmentsV1TypeV1 = {
    Identity: 'IDENTITY'
} as const;

export type OwnerreferencesegmentsV1TypeV1 = typeof OwnerreferencesegmentsV1TypeV1[keyof typeof OwnerreferencesegmentsV1TypeV1];

/**
 * 
 * @export
 * @interface SegmentV1
 */
export interface SegmentV1 {
    /**
     * The segment\'s ID.
     * @type {string}
     * @memberof SegmentV1
     */
    'id'?: string;
    /**
     * The segment\'s business name.
     * @type {string}
     * @memberof SegmentV1
     */
    'name'?: string;
    /**
     * The time when the segment is created.
     * @type {string}
     * @memberof SegmentV1
     */
    'created'?: string;
    /**
     * The time when the segment is modified.
     * @type {string}
     * @memberof SegmentV1
     */
    'modified'?: string;
    /**
     * The segment\'s optional description.
     * @type {string}
     * @memberof SegmentV1
     */
    'description'?: string;
    /**
     * 
     * @type {OwnerreferencesegmentsV1}
     * @memberof SegmentV1
     */
    'owner'?: OwnerreferencesegmentsV1 | null;
    /**
     * 
     * @type {SegmentVisibilityCriteriaV1}
     * @memberof SegmentV1
     */
    'visibilityCriteria'?: SegmentVisibilityCriteriaV1;
    /**
     * This boolean indicates whether the segment is currently active. Inactive segments have no effect.
     * @type {boolean}
     * @memberof SegmentV1
     */
    'active'?: boolean;
}
/**
 * 
 * @export
 * @interface SegmentVisibilityCriteriaV1
 */
export interface SegmentVisibilityCriteriaV1 {
    /**
     * 
     * @type {ExpressionV1}
     * @memberof SegmentVisibilityCriteriaV1
     */
    'expression'?: ExpressionV1;
}
/**
 * 
 * @export
 * @interface ValueV1
 */
export interface ValueV1 {
    /**
     * The type of attribute value
     * @type {string}
     * @memberof ValueV1
     */
    'type'?: string;
    /**
     * The attribute value
     * @type {string}
     * @memberof ValueV1
     */
    'value'?: string;
}
/**
 * 
 * @export
 * @interface VisibilitycriteriaV1
 */
export interface VisibilitycriteriaV1 {
    /**
     * 
     * @type {ExpressionV1}
     * @memberof VisibilitycriteriaV1
     */
    'expression'?: ExpressionV1;
}

/**
 * SegmentsV1Api - axios parameter creator
 * @export
 */
export const SegmentsV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This API creates a segment.  >**Note:** Segment definitions may take time to propagate to all identities.
         * @summary Create segment
         * @param {SegmentV1} segmentV1 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createSegmentV1: async (segmentV1: SegmentV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'segmentV1' is not null or undefined
            assertParamExists('createSegmentV1', 'segmentV1', segmentV1)
            const localVarPath = `/segments/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(segmentV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This API deletes the segment specified by the given ID. >**Note:** that segment deletion may take some time to become effective.    
         * @summary Delete segment by id
         * @param {string} id The segment ID to delete.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteSegmentV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteSegmentV1', 'id', id)
            const localVarPath = `/segments/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This API returns the segment specified by the given ID.
         * @summary Get segment by id
         * @param {string} id The segment ID to retrieve.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getSegmentV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getSegmentV1', 'id', id)
            const localVarPath = `/segments/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This API returns a list of all segments. 
         * @summary List segments
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listSegmentsV1: async (limit?: number, offset?: number, count?: boolean, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/segments/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Use this API to update segment fields by using the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard. >**Note:** Changes to a segment may take some time to propagate to all identities.
         * @summary Update segment
         * @param {string} id The segment ID to modify.
         * @param {Array<object>} requestBody A list of segment update operations according to the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard.  The following fields are patchable: * name * description * owner * visibilityCriteria * active 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        patchSegmentV1: async (id: string, requestBody: Array<object>, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('patchSegmentV1', 'id', id)
            // verify required parameter 'requestBody' is not null or undefined
            assertParamExists('patchSegmentV1', 'requestBody', requestBody)
            const localVarPath = `/segments/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PATCH', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json-patch+json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(requestBody, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * SegmentsV1Api - functional programming interface
 * @export
 */
export const SegmentsV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = SegmentsV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * This API creates a segment.  >**Note:** Segment definitions may take time to propagate to all identities.
         * @summary Create segment
         * @param {SegmentV1} segmentV1 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async createSegmentV1(segmentV1: SegmentV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SegmentV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createSegmentV1(segmentV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsV1Api.createSegmentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API deletes the segment specified by the given ID. >**Note:** that segment deletion may take some time to become effective.    
         * @summary Delete segment by id
         * @param {string} id The segment ID to delete.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async deleteSegmentV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteSegmentV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsV1Api.deleteSegmentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API returns the segment specified by the given ID.
         * @summary Get segment by id
         * @param {string} id The segment ID to retrieve.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getSegmentV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SegmentV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getSegmentV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsV1Api.getSegmentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API returns a list of all segments. 
         * @summary List segments
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async listSegmentsV1(limit?: number, offset?: number, count?: boolean, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<SegmentV1>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listSegmentsV1(limit, offset, count, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsV1Api.listSegmentsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Use this API to update segment fields by using the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard. >**Note:** Changes to a segment may take some time to propagate to all identities.
         * @summary Update segment
         * @param {string} id The segment ID to modify.
         * @param {Array<object>} requestBody A list of segment update operations according to the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard.  The following fields are patchable: * name * description * owner * visibilityCriteria * active 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async patchSegmentV1(id: string, requestBody: Array<object>, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<SegmentV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.patchSegmentV1(id, requestBody, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['SegmentsV1Api.patchSegmentV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * SegmentsV1Api - factory interface
 * @export
 */
export const SegmentsV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = SegmentsV1ApiFp(configuration)
    return {
        /**
         * This API creates a segment.  >**Note:** Segment definitions may take time to propagate to all identities.
         * @summary Create segment
         * @param {SegmentsV1ApiCreateSegmentV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createSegmentV1(requestParameters: SegmentsV1ApiCreateSegmentV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<SegmentV1> {
            return localVarFp.createSegmentV1(requestParameters.segmentV1, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This API deletes the segment specified by the given ID. >**Note:** that segment deletion may take some time to become effective.    
         * @summary Delete segment by id
         * @param {SegmentsV1ApiDeleteSegmentV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteSegmentV1(requestParameters: SegmentsV1ApiDeleteSegmentV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteSegmentV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This API returns the segment specified by the given ID.
         * @summary Get segment by id
         * @param {SegmentsV1ApiGetSegmentV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getSegmentV1(requestParameters: SegmentsV1ApiGetSegmentV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<SegmentV1> {
            return localVarFp.getSegmentV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This API returns a list of all segments. 
         * @summary List segments
         * @param {SegmentsV1ApiListSegmentsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listSegmentsV1(requestParameters: SegmentsV1ApiListSegmentsV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<SegmentV1>> {
            return localVarFp.listSegmentsV1(requestParameters.limit, requestParameters.offset, requestParameters.count, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Use this API to update segment fields by using the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard. >**Note:** Changes to a segment may take some time to propagate to all identities.
         * @summary Update segment
         * @param {SegmentsV1ApiPatchSegmentV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        patchSegmentV1(requestParameters: SegmentsV1ApiPatchSegmentV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<SegmentV1> {
            return localVarFp.patchSegmentV1(requestParameters.id, requestParameters.requestBody, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createSegmentV1 operation in SegmentsV1Api.
 * @export
 * @interface SegmentsV1ApiCreateSegmentV1Request
 */
export interface SegmentsV1ApiCreateSegmentV1Request {
    /**
     * 
     * @type {SegmentV1}
     * @memberof SegmentsV1ApiCreateSegmentV1
     */
    readonly segmentV1: SegmentV1
}

/**
 * Request parameters for deleteSegmentV1 operation in SegmentsV1Api.
 * @export
 * @interface SegmentsV1ApiDeleteSegmentV1Request
 */
export interface SegmentsV1ApiDeleteSegmentV1Request {
    /**
     * The segment ID to delete.
     * @type {string}
     * @memberof SegmentsV1ApiDeleteSegmentV1
     */
    readonly id: string
}

/**
 * Request parameters for getSegmentV1 operation in SegmentsV1Api.
 * @export
 * @interface SegmentsV1ApiGetSegmentV1Request
 */
export interface SegmentsV1ApiGetSegmentV1Request {
    /**
     * The segment ID to retrieve.
     * @type {string}
     * @memberof SegmentsV1ApiGetSegmentV1
     */
    readonly id: string
}

/**
 * Request parameters for listSegmentsV1 operation in SegmentsV1Api.
 * @export
 * @interface SegmentsV1ApiListSegmentsV1Request
 */
export interface SegmentsV1ApiListSegmentsV1Request {
    /**
     * Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof SegmentsV1ApiListSegmentsV1
     */
    readonly limit?: number

    /**
     * Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof SegmentsV1ApiListSegmentsV1
     */
    readonly offset?: number

    /**
     * If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {boolean}
     * @memberof SegmentsV1ApiListSegmentsV1
     */
    readonly count?: boolean
}

/**
 * Request parameters for patchSegmentV1 operation in SegmentsV1Api.
 * @export
 * @interface SegmentsV1ApiPatchSegmentV1Request
 */
export interface SegmentsV1ApiPatchSegmentV1Request {
    /**
     * The segment ID to modify.
     * @type {string}
     * @memberof SegmentsV1ApiPatchSegmentV1
     */
    readonly id: string

    /**
     * A list of segment update operations according to the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard.  The following fields are patchable: * name * description * owner * visibilityCriteria * active 
     * @type {Array<object>}
     * @memberof SegmentsV1ApiPatchSegmentV1
     */
    readonly requestBody: Array<object>
}

/**
 * SegmentsV1Api - object-oriented interface
 * @export
 * @class SegmentsV1Api
 * @extends {BaseAPI}
 */
export class SegmentsV1Api extends BaseAPI {
    /**
     * This API creates a segment.  >**Note:** Segment definitions may take time to propagate to all identities.
     * @summary Create segment
     * @param {SegmentsV1ApiCreateSegmentV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof SegmentsV1Api
     */
    public createSegmentV1(requestParameters: SegmentsV1ApiCreateSegmentV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return SegmentsV1ApiFp(this.configuration).createSegmentV1(requestParameters.segmentV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API deletes the segment specified by the given ID. >**Note:** that segment deletion may take some time to become effective.    
     * @summary Delete segment by id
     * @param {SegmentsV1ApiDeleteSegmentV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof SegmentsV1Api
     */
    public deleteSegmentV1(requestParameters: SegmentsV1ApiDeleteSegmentV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return SegmentsV1ApiFp(this.configuration).deleteSegmentV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API returns the segment specified by the given ID.
     * @summary Get segment by id
     * @param {SegmentsV1ApiGetSegmentV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof SegmentsV1Api
     */
    public getSegmentV1(requestParameters: SegmentsV1ApiGetSegmentV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return SegmentsV1ApiFp(this.configuration).getSegmentV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API returns a list of all segments. 
     * @summary List segments
     * @param {SegmentsV1ApiListSegmentsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof SegmentsV1Api
     */
    public listSegmentsV1(requestParameters: SegmentsV1ApiListSegmentsV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return SegmentsV1ApiFp(this.configuration).listSegmentsV1(requestParameters.limit, requestParameters.offset, requestParameters.count, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this API to update segment fields by using the [JSON Patch](https://tools.ietf.org/html/rfc6902) standard. >**Note:** Changes to a segment may take some time to propagate to all identities.
     * @summary Update segment
     * @param {SegmentsV1ApiPatchSegmentV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof SegmentsV1Api
     */
    public patchSegmentV1(requestParameters: SegmentsV1ApiPatchSegmentV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return SegmentsV1ApiFp(this.configuration).patchSegmentV1(requestParameters.id, requestParameters.requestBody, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



