/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Connector Rule Management
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ArgumentV1
 */
export interface ArgumentV1 {
    /**
     * the name of the argument
     * @type {string}
     * @memberof ArgumentV1
     */
    'name': string;
    /**
     * the description of the argument
     * @type {string}
     * @memberof ArgumentV1
     */
    'description'?: string | null;
    /**
     * the programmatic type of the argument
     * @type {string}
     * @memberof ArgumentV1
     */
    'type'?: string | null;
}
/**
 * The rule\'s function signature. Describes the rule\'s input arguments and output (if any)
 * @export
 * @interface ConnectorrulecreaterequestSignatureV1
 */
export interface ConnectorrulecreaterequestSignatureV1 {
    /**
     * 
     * @type {Array<ArgumentV1>}
     * @memberof ConnectorrulecreaterequestSignatureV1
     */
    'input': Array<ArgumentV1>;
    /**
     * 
     * @type {ArgumentV1}
     * @memberof ConnectorrulecreaterequestSignatureV1
     */
    'output'?: ArgumentV1 | null;
}
/**
 * ConnectorRuleCreateRequest
 * @export
 * @interface ConnectorrulecreaterequestV1
 */
export interface ConnectorrulecreaterequestV1 {
    /**
     * the name of the rule
     * @type {string}
     * @memberof ConnectorrulecreaterequestV1
     */
    'name': string;
    /**
     * a description of the rule\'s purpose
     * @type {string}
     * @memberof ConnectorrulecreaterequestV1
     */
    'description'?: string | null;
    /**
     * the type of rule
     * @type {string}
     * @memberof ConnectorrulecreaterequestV1
     */
    'type': ConnectorrulecreaterequestV1TypeV1;
    /**
     * 
     * @type {ConnectorrulecreaterequestSignatureV1}
     * @memberof ConnectorrulecreaterequestV1
     */
    'signature'?: ConnectorrulecreaterequestSignatureV1;
    /**
     * 
     * @type {SourcecodeV1}
     * @memberof ConnectorrulecreaterequestV1
     */
    'sourceCode': SourcecodeV1;
    /**
     * a map of string to objects
     * @type {object}
     * @memberof ConnectorrulecreaterequestV1
     */
    'attributes'?: object | null;
}

export const ConnectorrulecreaterequestV1TypeV1 = {
    BuildMap: 'BuildMap',
    ConnectorAfterCreate: 'ConnectorAfterCreate',
    ConnectorAfterDelete: 'ConnectorAfterDelete',
    ConnectorAfterModify: 'ConnectorAfterModify',
    ConnectorBeforeCreate: 'ConnectorBeforeCreate',
    ConnectorBeforeDelete: 'ConnectorBeforeDelete',
    ConnectorBeforeModify: 'ConnectorBeforeModify',
    JdbcBuildMap: 'JDBCBuildMap',
    JdbcOperationProvisioning: 'JDBCOperationProvisioning',
    JdbcProvision: 'JDBCProvision',
    PeopleSoftHrmsBuildMap: 'PeopleSoftHRMSBuildMap',
    PeopleSoftHrmsOperationProvisioning: 'PeopleSoftHRMSOperationProvisioning',
    PeopleSoftHrmsProvision: 'PeopleSoftHRMSProvision',
    RacfPermissionCustomization: 'RACFPermissionCustomization',
    ResourceObjectCustomization: 'ResourceObjectCustomization',
    SapBuildMap: 'SAPBuildMap',
    SapHrManagerRule: 'SapHrManagerRule',
    SapHrOperationProvisioning: 'SapHrOperationProvisioning',
    SapHrProvision: 'SapHrProvision',
    SuccessFactorsOperationProvisioning: 'SuccessFactorsOperationProvisioning',
    WebServiceAfterOperationRule: 'WebServiceAfterOperationRule',
    WebServiceBeforeOperationRule: 'WebServiceBeforeOperationRule',
    ResourceObjectCustomization2: 'ResourceObjectCustomization'
} as const;

export type ConnectorrulecreaterequestV1TypeV1 = typeof ConnectorrulecreaterequestV1TypeV1[keyof typeof ConnectorrulecreaterequestV1TypeV1];

/**
 * ConnectorRuleResponse
 * @export
 * @interface ConnectorruleresponseV1
 */
export interface ConnectorruleresponseV1 {
    /**
     * the name of the rule
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'name': string;
    /**
     * a description of the rule\'s purpose
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'description'?: string | null;
    /**
     * the type of rule
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'type': ConnectorruleresponseV1TypeV1;
    /**
     * 
     * @type {ConnectorrulecreaterequestSignatureV1}
     * @memberof ConnectorruleresponseV1
     */
    'signature'?: ConnectorrulecreaterequestSignatureV1;
    /**
     * 
     * @type {SourcecodeV1}
     * @memberof ConnectorruleresponseV1
     */
    'sourceCode': SourcecodeV1;
    /**
     * a map of string to objects
     * @type {object}
     * @memberof ConnectorruleresponseV1
     */
    'attributes'?: object | null;
    /**
     * the ID of the rule
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'id': string;
    /**
     * an ISO 8601 UTC timestamp when this rule was created
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'created': string;
    /**
     * an ISO 8601 UTC timestamp when this rule was last modified
     * @type {string}
     * @memberof ConnectorruleresponseV1
     */
    'modified'?: string | null;
}

export const ConnectorruleresponseV1TypeV1 = {
    BuildMap: 'BuildMap',
    ConnectorAfterCreate: 'ConnectorAfterCreate',
    ConnectorAfterDelete: 'ConnectorAfterDelete',
    ConnectorAfterModify: 'ConnectorAfterModify',
    ConnectorBeforeCreate: 'ConnectorBeforeCreate',
    ConnectorBeforeDelete: 'ConnectorBeforeDelete',
    ConnectorBeforeModify: 'ConnectorBeforeModify',
    JdbcBuildMap: 'JDBCBuildMap',
    JdbcOperationProvisioning: 'JDBCOperationProvisioning',
    JdbcProvision: 'JDBCProvision',
    PeopleSoftHrmsBuildMap: 'PeopleSoftHRMSBuildMap',
    PeopleSoftHrmsOperationProvisioning: 'PeopleSoftHRMSOperationProvisioning',
    PeopleSoftHrmsProvision: 'PeopleSoftHRMSProvision',
    RacfPermissionCustomization: 'RACFPermissionCustomization',
    ResourceObjectCustomization: 'ResourceObjectCustomization',
    SapBuildMap: 'SAPBuildMap',
    SapHrManagerRule: 'SapHrManagerRule',
    SapHrOperationProvisioning: 'SapHrOperationProvisioning',
    SapHrProvision: 'SapHrProvision',
    SuccessFactorsOperationProvisioning: 'SuccessFactorsOperationProvisioning',
    WebServiceAfterOperationRule: 'WebServiceAfterOperationRule',
    WebServiceBeforeOperationRule: 'WebServiceBeforeOperationRule',
    ResourceObjectCustomization2: 'ResourceObjectCustomization'
} as const;

export type ConnectorruleresponseV1TypeV1 = typeof ConnectorruleresponseV1TypeV1[keyof typeof ConnectorruleresponseV1TypeV1];

/**
 * ConnectorRuleUpdateRequest
 * @export
 * @interface ConnectorruleupdaterequestV1
 */
export interface ConnectorruleupdaterequestV1 {
    /**
     * the name of the rule
     * @type {string}
     * @memberof ConnectorruleupdaterequestV1
     */
    'name': string;
    /**
     * a description of the rule\'s purpose
     * @type {string}
     * @memberof ConnectorruleupdaterequestV1
     */
    'description'?: string | null;
    /**
     * the type of rule
     * @type {string}
     * @memberof ConnectorruleupdaterequestV1
     */
    'type': ConnectorruleupdaterequestV1TypeV1;
    /**
     * 
     * @type {ConnectorrulecreaterequestSignatureV1}
     * @memberof ConnectorruleupdaterequestV1
     */
    'signature'?: ConnectorrulecreaterequestSignatureV1;
    /**
     * 
     * @type {SourcecodeV1}
     * @memberof ConnectorruleupdaterequestV1
     */
    'sourceCode': SourcecodeV1;
    /**
     * a map of string to objects
     * @type {object}
     * @memberof ConnectorruleupdaterequestV1
     */
    'attributes'?: object | null;
    /**
     * the ID of the rule to update
     * @type {string}
     * @memberof ConnectorruleupdaterequestV1
     */
    'id': string;
}

export const ConnectorruleupdaterequestV1TypeV1 = {
    BuildMap: 'BuildMap',
    ConnectorAfterCreate: 'ConnectorAfterCreate',
    ConnectorAfterDelete: 'ConnectorAfterDelete',
    ConnectorAfterModify: 'ConnectorAfterModify',
    ConnectorBeforeCreate: 'ConnectorBeforeCreate',
    ConnectorBeforeDelete: 'ConnectorBeforeDelete',
    ConnectorBeforeModify: 'ConnectorBeforeModify',
    JdbcBuildMap: 'JDBCBuildMap',
    JdbcOperationProvisioning: 'JDBCOperationProvisioning',
    JdbcProvision: 'JDBCProvision',
    PeopleSoftHrmsBuildMap: 'PeopleSoftHRMSBuildMap',
    PeopleSoftHrmsOperationProvisioning: 'PeopleSoftHRMSOperationProvisioning',
    PeopleSoftHrmsProvision: 'PeopleSoftHRMSProvision',
    RacfPermissionCustomization: 'RACFPermissionCustomization',
    ResourceObjectCustomization: 'ResourceObjectCustomization',
    SapBuildMap: 'SAPBuildMap',
    SapHrManagerRule: 'SapHrManagerRule',
    SapHrOperationProvisioning: 'SapHrOperationProvisioning',
    SapHrProvision: 'SapHrProvision',
    SuccessFactorsOperationProvisioning: 'SuccessFactorsOperationProvisioning',
    WebServiceAfterOperationRule: 'WebServiceAfterOperationRule',
    WebServiceBeforeOperationRule: 'WebServiceBeforeOperationRule',
    ResourceObjectCustomization2: 'ResourceObjectCustomization'
} as const;

export type ConnectorruleupdaterequestV1TypeV1 = typeof ConnectorruleupdaterequestV1TypeV1[keyof typeof ConnectorruleupdaterequestV1TypeV1];

/**
 * CodeErrorDetail
 * @export
 * @interface ConnectorrulevalidationresponseDetailsInnerV1
 */
export interface ConnectorrulevalidationresponseDetailsInnerV1 {
    /**
     * The line number where the issue occurred
     * @type {number}
     * @memberof ConnectorrulevalidationresponseDetailsInnerV1
     */
    'line': number;
    /**
     * the column number where the issue occurred
     * @type {number}
     * @memberof ConnectorrulevalidationresponseDetailsInnerV1
     */
    'column': number;
    /**
     * a description of the issue in the code
     * @type {string}
     * @memberof ConnectorrulevalidationresponseDetailsInnerV1
     */
    'messsage'?: string;
}
/**
 * ConnectorRuleValidationResponse
 * @export
 * @interface ConnectorrulevalidationresponseV1
 */
export interface ConnectorrulevalidationresponseV1 {
    /**
     * 
     * @type {string}
     * @memberof ConnectorrulevalidationresponseV1
     */
    'state': ConnectorrulevalidationresponseV1StateV1;
    /**
     * 
     * @type {Array<ConnectorrulevalidationresponseDetailsInnerV1>}
     * @memberof ConnectorrulevalidationresponseV1
     */
    'details': Array<ConnectorrulevalidationresponseDetailsInnerV1>;
}

export const ConnectorrulevalidationresponseV1StateV1 = {
    Ok: 'OK',
    Error: 'ERROR'
} as const;

export type ConnectorrulevalidationresponseV1StateV1 = typeof ConnectorrulevalidationresponseV1StateV1[keyof typeof ConnectorrulevalidationresponseV1StateV1];

/**
 * 
 * @export
 * @interface ErrormessagedtoV1
 */
export interface ErrormessagedtoV1 {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleoriginV1}
     * @memberof ErrormessagedtoV1
     */
    'localeOrigin'?: LocaleoriginV1 | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorresponsedtoV1
 */
export interface ErrorresponsedtoV1 {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'messages'?: Array<ErrormessagedtoV1>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'causes'?: Array<ErrormessagedtoV1>;
}
/**
 * 
 * @export
 * @interface GetConnectorRuleListV1401ResponseV1
 */
export interface GetConnectorRuleListV1401ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetConnectorRuleListV1401ResponseV1
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface GetConnectorRuleListV1429ResponseV1
 */
export interface GetConnectorRuleListV1429ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetConnectorRuleListV1429ResponseV1
     */
    'message'?: any;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleoriginV1 = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleoriginV1 = typeof LocaleoriginV1[keyof typeof LocaleoriginV1];


/**
 * SourceCode
 * @export
 * @interface SourcecodeV1
 */
export interface SourcecodeV1 {
    /**
     * the version of the code
     * @type {string}
     * @memberof SourcecodeV1
     */
    'version': string;
    /**
     * The code
     * @type {string}
     * @memberof SourcecodeV1
     */
    'script': string;
}

/**
 * ConnectorRuleManagementV1Api - axios parameter creator
 * @export
 */
export const ConnectorRuleManagementV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Create a connector rule from the available types.
         * @summary Create connector rule
         * @param {ConnectorrulecreaterequestV1} connectorrulecreaterequestV1 Connector rule to create.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createConnectorRuleV1: async (connectorrulecreaterequestV1: ConnectorrulecreaterequestV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'connectorrulecreaterequestV1' is not null or undefined
            assertParamExists('createConnectorRuleV1', 'connectorrulecreaterequestV1', connectorrulecreaterequestV1)
            const localVarPath = `/connector-rules/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(connectorrulecreaterequestV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Delete the connector rule for the given ID.
         * @summary Delete connector rule
         * @param {string} id ID of the connector rule to delete.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteConnectorRuleV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteConnectorRuleV1', 'id', id)
            const localVarPath = `/connector-rules/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * List existing connector rules.
         * @summary List connector rules
         * @param {number} [limit] Note that for this API the maximum value for limit is 50. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getConnectorRuleListV1: async (limit?: number, offset?: number, count?: boolean, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/connector-rules/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Get a connector rule by ID.
         * @summary Get connector rule
         * @param {string} id ID of the connector rule to get.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getConnectorRuleV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getConnectorRuleV1', 'id', id)
            const localVarPath = `/connector-rules/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Update an existing connector rule with the one provided in the request body. These fields are immutable: `id`, `name`, `type`
         * @summary Update connector rule
         * @param {string} id ID of the connector rule to update.
         * @param {ConnectorruleupdaterequestV1} [connectorruleupdaterequestV1] Connector rule with updated data.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        putConnectorRuleV1: async (id: string, connectorruleupdaterequestV1?: ConnectorruleupdaterequestV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('putConnectorRuleV1', 'id', id)
            const localVarPath = `/connector-rules/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(connectorruleupdaterequestV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Detect issues within the connector rule\'s code to fix and list them.
         * @summary Validate connector rule
         * @param {SourcecodeV1} sourcecodeV1 Code to validate.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        testConnectorRuleV1: async (sourcecodeV1: SourcecodeV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourcecodeV1' is not null or undefined
            assertParamExists('testConnectorRuleV1', 'sourcecodeV1', sourcecodeV1)
            const localVarPath = `/connector-rules/v1/validate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(sourcecodeV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * ConnectorRuleManagementV1Api - functional programming interface
 * @export
 */
export const ConnectorRuleManagementV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ConnectorRuleManagementV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * Create a connector rule from the available types.
         * @summary Create connector rule
         * @param {ConnectorrulecreaterequestV1} connectorrulecreaterequestV1 Connector rule to create.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async createConnectorRuleV1(connectorrulecreaterequestV1: ConnectorrulecreaterequestV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectorruleresponseV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createConnectorRuleV1(connectorrulecreaterequestV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.createConnectorRuleV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Delete the connector rule for the given ID.
         * @summary Delete connector rule
         * @param {string} id ID of the connector rule to delete.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async deleteConnectorRuleV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteConnectorRuleV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.deleteConnectorRuleV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * List existing connector rules.
         * @summary List connector rules
         * @param {number} [limit] Note that for this API the maximum value for limit is 50. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getConnectorRuleListV1(limit?: number, offset?: number, count?: boolean, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<ConnectorruleresponseV1>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConnectorRuleListV1(limit, offset, count, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.getConnectorRuleListV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get a connector rule by ID.
         * @summary Get connector rule
         * @param {string} id ID of the connector rule to get.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getConnectorRuleV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectorruleresponseV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getConnectorRuleV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.getConnectorRuleV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Update an existing connector rule with the one provided in the request body. These fields are immutable: `id`, `name`, `type`
         * @summary Update connector rule
         * @param {string} id ID of the connector rule to update.
         * @param {ConnectorruleupdaterequestV1} [connectorruleupdaterequestV1] Connector rule with updated data.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async putConnectorRuleV1(id: string, connectorruleupdaterequestV1?: ConnectorruleupdaterequestV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectorruleresponseV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.putConnectorRuleV1(id, connectorruleupdaterequestV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.putConnectorRuleV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Detect issues within the connector rule\'s code to fix and list them.
         * @summary Validate connector rule
         * @param {SourcecodeV1} sourcecodeV1 Code to validate.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async testConnectorRuleV1(sourcecodeV1: SourcecodeV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ConnectorrulevalidationresponseV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.testConnectorRuleV1(sourcecodeV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ConnectorRuleManagementV1Api.testConnectorRuleV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ConnectorRuleManagementV1Api - factory interface
 * @export
 */
export const ConnectorRuleManagementV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ConnectorRuleManagementV1ApiFp(configuration)
    return {
        /**
         * Create a connector rule from the available types.
         * @summary Create connector rule
         * @param {ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<ConnectorruleresponseV1> {
            return localVarFp.createConnectorRuleV1(requestParameters.connectorrulecreaterequestV1, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Delete the connector rule for the given ID.
         * @summary Delete connector rule
         * @param {ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteConnectorRuleV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * List existing connector rules.
         * @summary List connector rules
         * @param {ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getConnectorRuleListV1(requestParameters: ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<ConnectorruleresponseV1>> {
            return localVarFp.getConnectorRuleListV1(requestParameters.limit, requestParameters.offset, requestParameters.count, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Get a connector rule by ID.
         * @summary Get connector rule
         * @param {ConnectorRuleManagementV1ApiGetConnectorRuleV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiGetConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<ConnectorruleresponseV1> {
            return localVarFp.getConnectorRuleV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Update an existing connector rule with the one provided in the request body. These fields are immutable: `id`, `name`, `type`
         * @summary Update connector rule
         * @param {ConnectorRuleManagementV1ApiPutConnectorRuleV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        putConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiPutConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<ConnectorruleresponseV1> {
            return localVarFp.putConnectorRuleV1(requestParameters.id, requestParameters.connectorruleupdaterequestV1, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Detect issues within the connector rule\'s code to fix and list them.
         * @summary Validate connector rule
         * @param {ConnectorRuleManagementV1ApiTestConnectorRuleV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        testConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiTestConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<ConnectorrulevalidationresponseV1> {
            return localVarFp.testConnectorRuleV1(requestParameters.sourcecodeV1, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createConnectorRuleV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request
 */
export interface ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request {
    /**
     * Connector rule to create.
     * @type {ConnectorrulecreaterequestV1}
     * @memberof ConnectorRuleManagementV1ApiCreateConnectorRuleV1
     */
    readonly connectorrulecreaterequestV1: ConnectorrulecreaterequestV1
}

/**
 * Request parameters for deleteConnectorRuleV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request
 */
export interface ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request {
    /**
     * ID of the connector rule to delete.
     * @type {string}
     * @memberof ConnectorRuleManagementV1ApiDeleteConnectorRuleV1
     */
    readonly id: string
}

/**
 * Request parameters for getConnectorRuleListV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request
 */
export interface ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request {
    /**
     * Note that for this API the maximum value for limit is 50. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof ConnectorRuleManagementV1ApiGetConnectorRuleListV1
     */
    readonly limit?: number

    /**
     * Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof ConnectorRuleManagementV1ApiGetConnectorRuleListV1
     */
    readonly offset?: number

    /**
     * If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {boolean}
     * @memberof ConnectorRuleManagementV1ApiGetConnectorRuleListV1
     */
    readonly count?: boolean
}

/**
 * Request parameters for getConnectorRuleV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiGetConnectorRuleV1Request
 */
export interface ConnectorRuleManagementV1ApiGetConnectorRuleV1Request {
    /**
     * ID of the connector rule to get.
     * @type {string}
     * @memberof ConnectorRuleManagementV1ApiGetConnectorRuleV1
     */
    readonly id: string
}

/**
 * Request parameters for putConnectorRuleV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiPutConnectorRuleV1Request
 */
export interface ConnectorRuleManagementV1ApiPutConnectorRuleV1Request {
    /**
     * ID of the connector rule to update.
     * @type {string}
     * @memberof ConnectorRuleManagementV1ApiPutConnectorRuleV1
     */
    readonly id: string

    /**
     * Connector rule with updated data.
     * @type {ConnectorruleupdaterequestV1}
     * @memberof ConnectorRuleManagementV1ApiPutConnectorRuleV1
     */
    readonly connectorruleupdaterequestV1?: ConnectorruleupdaterequestV1
}

/**
 * Request parameters for testConnectorRuleV1 operation in ConnectorRuleManagementV1Api.
 * @export
 * @interface ConnectorRuleManagementV1ApiTestConnectorRuleV1Request
 */
export interface ConnectorRuleManagementV1ApiTestConnectorRuleV1Request {
    /**
     * Code to validate.
     * @type {SourcecodeV1}
     * @memberof ConnectorRuleManagementV1ApiTestConnectorRuleV1
     */
    readonly sourcecodeV1: SourcecodeV1
}

/**
 * ConnectorRuleManagementV1Api - object-oriented interface
 * @export
 * @class ConnectorRuleManagementV1Api
 * @extends {BaseAPI}
 */
export class ConnectorRuleManagementV1Api extends BaseAPI {
    /**
     * Create a connector rule from the available types.
     * @summary Create connector rule
     * @param {ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public createConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiCreateConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).createConnectorRuleV1(requestParameters.connectorrulecreaterequestV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Delete the connector rule for the given ID.
     * @summary Delete connector rule
     * @param {ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public deleteConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiDeleteConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).deleteConnectorRuleV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * List existing connector rules.
     * @summary List connector rules
     * @param {ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public getConnectorRuleListV1(requestParameters: ConnectorRuleManagementV1ApiGetConnectorRuleListV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).getConnectorRuleListV1(requestParameters.limit, requestParameters.offset, requestParameters.count, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get a connector rule by ID.
     * @summary Get connector rule
     * @param {ConnectorRuleManagementV1ApiGetConnectorRuleV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public getConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiGetConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).getConnectorRuleV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Update an existing connector rule with the one provided in the request body. These fields are immutable: `id`, `name`, `type`
     * @summary Update connector rule
     * @param {ConnectorRuleManagementV1ApiPutConnectorRuleV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public putConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiPutConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).putConnectorRuleV1(requestParameters.id, requestParameters.connectorruleupdaterequestV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Detect issues within the connector rule\'s code to fix and list them.
     * @summary Validate connector rule
     * @param {ConnectorRuleManagementV1ApiTestConnectorRuleV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ConnectorRuleManagementV1Api
     */
    public testConnectorRuleV1(requestParameters: ConnectorRuleManagementV1ApiTestConnectorRuleV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ConnectorRuleManagementV1ApiFp(this.configuration).testConnectorRuleV1(requestParameters.sourcecodeV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



