/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Transforms
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrormessagedtoV1
 */
export interface ErrormessagedtoV1 {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleoriginV1}
     * @memberof ErrormessagedtoV1
     */
    'localeOrigin'?: LocaleoriginV1 | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorresponsedtoV1
 */
export interface ErrorresponsedtoV1 {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'messages'?: Array<ErrormessagedtoV1>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'causes'?: Array<ErrormessagedtoV1>;
}
/**
 * 
 * @export
 * @interface ListTransformsV1401ResponseV1
 */
export interface ListTransformsV1401ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListTransformsV1401ResponseV1
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface ListTransformsV1429ResponseV1
 */
export interface ListTransformsV1429ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListTransformsV1429ResponseV1
     */
    'message'?: any;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleoriginV1 = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleoriginV1 = typeof LocaleoriginV1[keyof typeof LocaleoriginV1];


/**
 * The representation of an internally- or customer-defined transform.
 * @export
 * @interface TransformV1
 */
export interface TransformV1 {
    /**
     * Unique name of this transform
     * @type {string}
     * @memberof TransformV1
     */
    'name': string;
    /**
     * The type of transform operation
     * @type {string}
     * @memberof TransformV1
     */
    'type': TransformV1TypeV1;
    /**
     * Meta-data about the transform. Values in this list are specific to the type of transform to be executed.
     * @type {object}
     * @memberof TransformV1
     */
    'attributes': object | null;
}

export const TransformV1TypeV1 = {
    AccountAttribute: 'accountAttribute',
    Base64Decode: 'base64Decode',
    Base64Encode: 'base64Encode',
    Concat: 'concat',
    Conditional: 'conditional',
    DateCompare: 'dateCompare',
    DateFormat: 'dateFormat',
    DateMath: 'dateMath',
    DecomposeDiacriticalMarks: 'decomposeDiacriticalMarks',
    E164phone: 'e164phone',
    FirstValid: 'firstValid',
    Rule: 'rule',
    IdentityAttribute: 'identityAttribute',
    IndexOf: 'indexOf',
    Iso3166: 'iso3166',
    LastIndexOf: 'lastIndexOf',
    LeftPad: 'leftPad',
    Lookup: 'lookup',
    Lower: 'lower',
    NormalizeNames: 'normalizeNames',
    RandomAlphaNumeric: 'randomAlphaNumeric',
    RandomNumeric: 'randomNumeric',
    Reference: 'reference',
    ReplaceAll: 'replaceAll',
    Replace: 'replace',
    RightPad: 'rightPad',
    Split: 'split',
    Static: 'static',
    Substring: 'substring',
    Trim: 'trim',
    Upper: 'upper',
    UsernameGenerator: 'usernameGenerator',
    Uuid: 'uuid',
    DisplayName: 'displayName',
    Rfc5646: 'rfc5646'
} as const;

export type TransformV1TypeV1 = typeof TransformV1TypeV1[keyof typeof TransformV1TypeV1];

/**
 * 
 * @export
 * @interface TransformreadV1
 */
export interface TransformreadV1 {
    /**
     * Unique name of this transform
     * @type {string}
     * @memberof TransformreadV1
     */
    'name': string;
    /**
     * The type of transform operation
     * @type {string}
     * @memberof TransformreadV1
     */
    'type': TransformreadV1TypeV1;
    /**
     * Meta-data about the transform. Values in this list are specific to the type of transform to be executed.
     * @type {object}
     * @memberof TransformreadV1
     */
    'attributes': object | null;
    /**
     * Unique ID of this transform
     * @type {string}
     * @memberof TransformreadV1
     */
    'id': string;
    /**
     * Indicates whether this is an internal SailPoint-created transform or a customer-created transform
     * @type {boolean}
     * @memberof TransformreadV1
     */
    'internal': boolean;
}

export const TransformreadV1TypeV1 = {
    AccountAttribute: 'accountAttribute',
    Base64Decode: 'base64Decode',
    Base64Encode: 'base64Encode',
    Concat: 'concat',
    Conditional: 'conditional',
    DateCompare: 'dateCompare',
    DateFormat: 'dateFormat',
    DateMath: 'dateMath',
    DecomposeDiacriticalMarks: 'decomposeDiacriticalMarks',
    E164phone: 'e164phone',
    FirstValid: 'firstValid',
    Rule: 'rule',
    IdentityAttribute: 'identityAttribute',
    IndexOf: 'indexOf',
    Iso3166: 'iso3166',
    LastIndexOf: 'lastIndexOf',
    LeftPad: 'leftPad',
    Lookup: 'lookup',
    Lower: 'lower',
    NormalizeNames: 'normalizeNames',
    RandomAlphaNumeric: 'randomAlphaNumeric',
    RandomNumeric: 'randomNumeric',
    Reference: 'reference',
    ReplaceAll: 'replaceAll',
    Replace: 'replace',
    RightPad: 'rightPad',
    Split: 'split',
    Static: 'static',
    Substring: 'substring',
    Trim: 'trim',
    Upper: 'upper',
    UsernameGenerator: 'usernameGenerator',
    Uuid: 'uuid',
    DisplayName: 'displayName',
    Rfc5646: 'rfc5646'
} as const;

export type TransformreadV1TypeV1 = typeof TransformreadV1TypeV1[keyof typeof TransformreadV1TypeV1];


/**
 * TransformsV1Api - axios parameter creator
 * @export
 */
export const TransformsV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a new transform object immediately. By default, the internal flag is set to false to indicate that this is a custom transform. Only SailPoint employees have the ability to create a transform with internal set to true. Newly created Transforms can be used in the Identity Profile mappings within the UI.
         * @summary Create transform
         * @param {TransformV1} transformV1 The transform to be created.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createTransformV1: async (transformV1: TransformV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'transformV1' is not null or undefined
            assertParamExists('createTransformV1', 'transformV1', transformV1)
            const localVarPath = `/transforms/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transformV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Deletes the transform specified by the given ID. Attempting to delete a transform that is used in one or more Identity Profile mappings will result in an error. If this occurs, you must first remove the transform from all mappings before deleting the transform.
         * @summary Delete a transform
         * @param {string} id ID of the transform to delete
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteTransformV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('deleteTransformV1', 'id', id)
            const localVarPath = `/transforms/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This API returns the transform specified by the given ID.
         * @summary Transform by id
         * @param {string} id ID of the transform to retrieve
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTransformV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('getTransformV1', 'id', id)
            const localVarPath = `/transforms/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Gets a list of all saved transform objects.
         * @summary List transforms
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {string} [name] Name of the transform to retrieve from the list.
         * @param {string} [filters] Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **internal**: *eq*  **name**: *eq, sw*
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listTransformsV1: async (offset?: number, limit?: number, count?: boolean, name?: string, filters?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/transforms/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (count !== undefined) {
                localVarQueryParameter['count'] = count;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (filters !== undefined) {
                localVarQueryParameter['filters'] = filters;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Replaces the transform specified by the given ID with the transform provided in the request body. Only the \"attributes\" field is mutable. Attempting to change other properties (ex. \"name\" and \"type\") will result in an error.
         * @summary Update a transform
         * @param {string} id ID of the transform to update
         * @param {TransformV1} [transformV1] The updated transform object. Must include \&quot;name\&quot;, \&quot;type\&quot;, and \&quot;attributes\&quot; fields, but \&quot;name\&quot; and \&quot;type\&quot; must not be modified.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updateTransformV1: async (id: string, transformV1?: TransformV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('updateTransformV1', 'id', id)
            const localVarPath = `/transforms/v1/{id}`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(transformV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * TransformsV1Api - functional programming interface
 * @export
 */
export const TransformsV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TransformsV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a new transform object immediately. By default, the internal flag is set to false to indicate that this is a custom transform. Only SailPoint employees have the ability to create a transform with internal set to true. Newly created Transforms can be used in the Identity Profile mappings within the UI.
         * @summary Create transform
         * @param {TransformV1} transformV1 The transform to be created.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async createTransformV1(transformV1: TransformV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransformreadV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createTransformV1(transformV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsV1Api.createTransformV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Deletes the transform specified by the given ID. Attempting to delete a transform that is used in one or more Identity Profile mappings will result in an error. If this occurs, you must first remove the transform from all mappings before deleting the transform.
         * @summary Delete a transform
         * @param {string} id ID of the transform to delete
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async deleteTransformV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteTransformV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsV1Api.deleteTransformV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This API returns the transform specified by the given ID.
         * @summary Transform by id
         * @param {string} id ID of the transform to retrieve
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getTransformV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransformreadV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getTransformV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsV1Api.getTransformV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a list of all saved transform objects.
         * @summary List transforms
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {boolean} [count] If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {string} [name] Name of the transform to retrieve from the list.
         * @param {string} [filters] Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **internal**: *eq*  **name**: *eq, sw*
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async listTransformsV1(offset?: number, limit?: number, count?: boolean, name?: string, filters?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<TransformreadV1>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listTransformsV1(offset, limit, count, name, filters, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsV1Api.listTransformsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Replaces the transform specified by the given ID with the transform provided in the request body. Only the \"attributes\" field is mutable. Attempting to change other properties (ex. \"name\" and \"type\") will result in an error.
         * @summary Update a transform
         * @param {string} id ID of the transform to update
         * @param {TransformV1} [transformV1] The updated transform object. Must include \&quot;name\&quot;, \&quot;type\&quot;, and \&quot;attributes\&quot; fields, but \&quot;name\&quot; and \&quot;type\&quot; must not be modified.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async updateTransformV1(id: string, transformV1?: TransformV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<TransformreadV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateTransformV1(id, transformV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TransformsV1Api.updateTransformV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TransformsV1Api - factory interface
 * @export
 */
export const TransformsV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TransformsV1ApiFp(configuration)
    return {
        /**
         * Creates a new transform object immediately. By default, the internal flag is set to false to indicate that this is a custom transform. Only SailPoint employees have the ability to create a transform with internal set to true. Newly created Transforms can be used in the Identity Profile mappings within the UI.
         * @summary Create transform
         * @param {TransformsV1ApiCreateTransformV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createTransformV1(requestParameters: TransformsV1ApiCreateTransformV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<TransformreadV1> {
            return localVarFp.createTransformV1(requestParameters.transformV1, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Deletes the transform specified by the given ID. Attempting to delete a transform that is used in one or more Identity Profile mappings will result in an error. If this occurs, you must first remove the transform from all mappings before deleting the transform.
         * @summary Delete a transform
         * @param {TransformsV1ApiDeleteTransformV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteTransformV1(requestParameters: TransformsV1ApiDeleteTransformV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteTransformV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This API returns the transform specified by the given ID.
         * @summary Transform by id
         * @param {TransformsV1ApiGetTransformV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getTransformV1(requestParameters: TransformsV1ApiGetTransformV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<TransformreadV1> {
            return localVarFp.getTransformV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Gets a list of all saved transform objects.
         * @summary List transforms
         * @param {TransformsV1ApiListTransformsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listTransformsV1(requestParameters: TransformsV1ApiListTransformsV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<TransformreadV1>> {
            return localVarFp.listTransformsV1(requestParameters.offset, requestParameters.limit, requestParameters.count, requestParameters.name, requestParameters.filters, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Replaces the transform specified by the given ID with the transform provided in the request body. Only the \"attributes\" field is mutable. Attempting to change other properties (ex. \"name\" and \"type\") will result in an error.
         * @summary Update a transform
         * @param {TransformsV1ApiUpdateTransformV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updateTransformV1(requestParameters: TransformsV1ApiUpdateTransformV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<TransformreadV1> {
            return localVarFp.updateTransformV1(requestParameters.id, requestParameters.transformV1, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createTransformV1 operation in TransformsV1Api.
 * @export
 * @interface TransformsV1ApiCreateTransformV1Request
 */
export interface TransformsV1ApiCreateTransformV1Request {
    /**
     * The transform to be created.
     * @type {TransformV1}
     * @memberof TransformsV1ApiCreateTransformV1
     */
    readonly transformV1: TransformV1
}

/**
 * Request parameters for deleteTransformV1 operation in TransformsV1Api.
 * @export
 * @interface TransformsV1ApiDeleteTransformV1Request
 */
export interface TransformsV1ApiDeleteTransformV1Request {
    /**
     * ID of the transform to delete
     * @type {string}
     * @memberof TransformsV1ApiDeleteTransformV1
     */
    readonly id: string
}

/**
 * Request parameters for getTransformV1 operation in TransformsV1Api.
 * @export
 * @interface TransformsV1ApiGetTransformV1Request
 */
export interface TransformsV1ApiGetTransformV1Request {
    /**
     * ID of the transform to retrieve
     * @type {string}
     * @memberof TransformsV1ApiGetTransformV1
     */
    readonly id: string
}

/**
 * Request parameters for listTransformsV1 operation in TransformsV1Api.
 * @export
 * @interface TransformsV1ApiListTransformsV1Request
 */
export interface TransformsV1ApiListTransformsV1Request {
    /**
     * Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof TransformsV1ApiListTransformsV1
     */
    readonly offset?: number

    /**
     * Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof TransformsV1ApiListTransformsV1
     */
    readonly limit?: number

    /**
     * If *true* it will populate the *X-Total-Count* response header with the number of results that would be returned if *limit* and *offset* were ignored.  Since requesting a total count can have a performance impact, it is recommended not to send **count&#x3D;true** if that value will not be used.  See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {boolean}
     * @memberof TransformsV1ApiListTransformsV1
     */
    readonly count?: boolean

    /**
     * Name of the transform to retrieve from the list.
     * @type {string}
     * @memberof TransformsV1ApiListTransformsV1
     */
    readonly name?: string

    /**
     * Filter results using the standard syntax described in [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters#filtering-results)  Filtering is supported for the following fields and operators:  **internal**: *eq*  **name**: *eq, sw*
     * @type {string}
     * @memberof TransformsV1ApiListTransformsV1
     */
    readonly filters?: string
}

/**
 * Request parameters for updateTransformV1 operation in TransformsV1Api.
 * @export
 * @interface TransformsV1ApiUpdateTransformV1Request
 */
export interface TransformsV1ApiUpdateTransformV1Request {
    /**
     * ID of the transform to update
     * @type {string}
     * @memberof TransformsV1ApiUpdateTransformV1
     */
    readonly id: string

    /**
     * The updated transform object. Must include \&quot;name\&quot;, \&quot;type\&quot;, and \&quot;attributes\&quot; fields, but \&quot;name\&quot; and \&quot;type\&quot; must not be modified.
     * @type {TransformV1}
     * @memberof TransformsV1ApiUpdateTransformV1
     */
    readonly transformV1?: TransformV1
}

/**
 * TransformsV1Api - object-oriented interface
 * @export
 * @class TransformsV1Api
 * @extends {BaseAPI}
 */
export class TransformsV1Api extends BaseAPI {
    /**
     * Creates a new transform object immediately. By default, the internal flag is set to false to indicate that this is a custom transform. Only SailPoint employees have the ability to create a transform with internal set to true. Newly created Transforms can be used in the Identity Profile mappings within the UI.
     * @summary Create transform
     * @param {TransformsV1ApiCreateTransformV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsV1Api
     */
    public createTransformV1(requestParameters: TransformsV1ApiCreateTransformV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TransformsV1ApiFp(this.configuration).createTransformV1(requestParameters.transformV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Deletes the transform specified by the given ID. Attempting to delete a transform that is used in one or more Identity Profile mappings will result in an error. If this occurs, you must first remove the transform from all mappings before deleting the transform.
     * @summary Delete a transform
     * @param {TransformsV1ApiDeleteTransformV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsV1Api
     */
    public deleteTransformV1(requestParameters: TransformsV1ApiDeleteTransformV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TransformsV1ApiFp(this.configuration).deleteTransformV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This API returns the transform specified by the given ID.
     * @summary Transform by id
     * @param {TransformsV1ApiGetTransformV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsV1Api
     */
    public getTransformV1(requestParameters: TransformsV1ApiGetTransformV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TransformsV1ApiFp(this.configuration).getTransformV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a list of all saved transform objects.
     * @summary List transforms
     * @param {TransformsV1ApiListTransformsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsV1Api
     */
    public listTransformsV1(requestParameters: TransformsV1ApiListTransformsV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return TransformsV1ApiFp(this.configuration).listTransformsV1(requestParameters.offset, requestParameters.limit, requestParameters.count, requestParameters.name, requestParameters.filters, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Replaces the transform specified by the given ID with the transform provided in the request body. Only the \"attributes\" field is mutable. Attempting to change other properties (ex. \"name\" and \"type\") will result in an error.
     * @summary Update a transform
     * @param {TransformsV1ApiUpdateTransformV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof TransformsV1Api
     */
    public updateTransformV1(requestParameters: TransformsV1ApiUpdateTransformV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return TransformsV1ApiFp(this.configuration).updateTransformV1(requestParameters.id, requestParameters.transformV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



