templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-nerm-sdk
npmRepository: sailpoint.com
npmVersion: 2.0.10
useSingleRequestParameter: true
apiVersion: v2025
enumNameSuffix: NermV2025
nerm: true
