templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-nerm-sdk
npmRepository: sailpoint.com
npmVersion: 1.8.3
useSingleRequestParameter: true
enumNameSuffix: Nerm
nerm: true
