templateDir: ./sdk-resources/resources
files:
  package.mustache:
    templateType: SupportingFiles
    destinationFilename: package.json
npmName: sailpoint-nerm-sdk
npmRepository: sailpoint.com
npmVersion: 1.8.0
useSingleRequestParameter: true
apiVersion: 2025
enumNameSuffix: NermV2025
nerm: true
