/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Machine Account Mappings
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface AttributeMappings
 */
export interface AttributeMappings {
    /**
     * 
     * @type {AttributeMappingsAllOfTarget}
     * @memberof AttributeMappings
     */
    'target'?: AttributeMappingsAllOfTarget;
    /**
     * 
     * @type {AttributeMappingsAllOfTransformDefinition}
     * @memberof AttributeMappings
     */
    'transformDefinition'?: AttributeMappingsAllOfTransformDefinition;
}
/**
 * Targeted Entity
 * @export
 * @interface AttributeMappingsAllOfTarget
 */
export interface AttributeMappingsAllOfTarget {
    /**
     * The type of target entity
     * @type {string}
     * @memberof AttributeMappingsAllOfTarget
     */
    'type'?: AttributeMappingsAllOfTargetTypeEnum;
    /**
     * Name of the targeted attribute
     * @type {string}
     * @memberof AttributeMappingsAllOfTarget
     */
    'attributeName'?: string;
    /**
     * The ID of Source
     * @type {string}
     * @memberof AttributeMappingsAllOfTarget
     */
    'sourceId'?: string;
}

export const AttributeMappingsAllOfTargetTypeEnum = {
    Account: 'ACCOUNT',
    Identity: 'IDENTITY',
    OwnerAccount: 'OWNER_ACCOUNT',
    OwnerIdentity: 'OWNER_IDENTITY'
} as const;

export type AttributeMappingsAllOfTargetTypeEnum = typeof AttributeMappingsAllOfTargetTypeEnum[keyof typeof AttributeMappingsAllOfTargetTypeEnum];

/**
 * 
 * @export
 * @interface AttributeMappingsAllOfTransformDefinition
 */
export interface AttributeMappingsAllOfTransformDefinition {
    /**
     * The type of transform
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinition
     */
    'type'?: string;
    /**
     * 
     * @type {AttributeMappingsAllOfTransformDefinitionAttributes}
     * @memberof AttributeMappingsAllOfTransformDefinition
     */
    'attributes'?: AttributeMappingsAllOfTransformDefinitionAttributes;
    /**
     * Transform Operation
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinition
     */
    'id'?: string;
}
/**
 * attributes object
 * @export
 * @interface AttributeMappingsAllOfTransformDefinitionAttributes
 */
export interface AttributeMappingsAllOfTransformDefinitionAttributes {
    /**
     * 
     * @type {AttributeMappingsAllOfTransformDefinitionAttributesInput}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributes
     */
    'input'?: AttributeMappingsAllOfTransformDefinitionAttributesInput;
}
/**
 * Input Object
 * @export
 * @interface AttributeMappingsAllOfTransformDefinitionAttributesInput
 */
export interface AttributeMappingsAllOfTransformDefinitionAttributesInput {
    /**
     * The Type of Attribute
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributesInput
     */
    'type'?: string;
    /**
     * 
     * @type {AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributesInput
     */
    'attributes'?: AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes;
}
/**
 * Attibute Mapping Object
 * @export
 * @interface AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes
 */
export interface AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes {
    /**
     * The name of attribute
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes
     */
    'attributeName'?: string;
    /**
     * Name of the Source
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes
     */
    'sourceName'?: string;
    /**
     * ID of the Source
     * @type {string}
     * @memberof AttributeMappingsAllOfTransformDefinitionAttributesInputAttributes
     */
    'name'?: string;
}
/**
 * 
 * @export
 * @interface ErrorMessageDto
 */
export interface ErrorMessageDto {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrorMessageDto
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleOrigin}
     * @memberof ErrorMessageDto
     */
    'localeOrigin'?: LocaleOrigin | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrorMessageDto
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorResponseDto
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorResponseDto
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrorMessageDto>}
     * @memberof ErrorResponseDto
     */
    'messages'?: Array<ErrorMessageDto>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrorMessageDto>}
     * @memberof ErrorResponseDto
     */
    'causes'?: Array<ErrorMessageDto>;
}
/**
 * 
 * @export
 * @interface ListMachineAccountMappingsV1401Response
 */
export interface ListMachineAccountMappingsV1401Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListMachineAccountMappingsV1401Response
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface ListMachineAccountMappingsV1429Response
 */
export interface ListMachineAccountMappingsV1429Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof ListMachineAccountMappingsV1429Response
     */
    'message'?: any;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleOrigin = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleOrigin = typeof LocaleOrigin[keyof typeof LocaleOrigin];



/**
 * MachineAccountMappingsApi - axios parameter creator
 * @export
 */
export const MachineAccountMappingsApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates Machine Account Mappings for both identities and accounts for a source. A token with API, ORG_ADMIN, ROLE_ADMIN, ROLE_SUBADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Create machine account mappings
         * @param {string} sourceId Source ID.
         * @param {AttributeMappings} attributeMappings 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createMachineAccountMappingsV1: async (sourceId: string, attributeMappings: AttributeMappings, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourceId' is not null or undefined
            assertParamExists('createMachineAccountMappingsV1', 'sourceId', sourceId)
            // verify required parameter 'attributeMappings' is not null or undefined
            assertParamExists('createMachineAccountMappingsV1', 'attributeMappings', attributeMappings)
            const localVarPath = `/sources/v1/{sourceId}/machine-account-mappings`
                .replace(`{${"sourceId"}}`, encodeURIComponent(String(sourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(attributeMappings, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Use this API to remove machine account attribute mappings for a Source.  A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Delete source\'s machine account mappings
         * @param {string} sourceId source ID.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteMachineAccountMappingsV1: async (sourceId: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourceId' is not null or undefined
            assertParamExists('deleteMachineAccountMappingsV1', 'sourceId', sourceId)
            const localVarPath = `/sources/v1/{sourceId}/machine-account-mappings`
                .replace(`{${"sourceId"}}`, encodeURIComponent(String(sourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Retrieves Machine account mappings for a specified source using Source ID.
         * @summary Machine account mapping for source
         * @param {string} sourceId Source ID
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listMachineAccountMappingsV1: async (sourceId: string, limit?: number, offset?: number, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourceId' is not null or undefined
            assertParamExists('listMachineAccountMappingsV1', 'sourceId', sourceId)
            const localVarPath = `/sources/v1/{sourceId}/machine-account-mappings`
                .replace(`{${"sourceId"}}`, encodeURIComponent(String(sourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (limit !== undefined) {
                localVarQueryParameter['limit'] = limit;
            }

            if (offset !== undefined) {
                localVarQueryParameter['offset'] = offset;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Use this API to update Machine Account Attribute Mapping for a Source. A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Update source\'s machine account mappings
         * @param {string} sourceId Source ID.
         * @param {AttributeMappings} attributeMappings 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        setMachineAccountMappingsV1: async (sourceId: string, attributeMappings: AttributeMappings, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'sourceId' is not null or undefined
            assertParamExists('setMachineAccountMappingsV1', 'sourceId', sourceId)
            // verify required parameter 'attributeMappings' is not null or undefined
            assertParamExists('setMachineAccountMappingsV1', 'attributeMappings', attributeMappings)
            const localVarPath = `/sources/v1/{sourceId}/machine-mappings`
                .replace(`{${"sourceId"}}`, encodeURIComponent(String(sourceId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(attributeMappings, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * MachineAccountMappingsApi - functional programming interface
 * @export
 */
export const MachineAccountMappingsApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = MachineAccountMappingsApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates Machine Account Mappings for both identities and accounts for a source. A token with API, ORG_ADMIN, ROLE_ADMIN, ROLE_SUBADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Create machine account mappings
         * @param {string} sourceId Source ID.
         * @param {AttributeMappings} attributeMappings 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async createMachineAccountMappingsV1(sourceId: string, attributeMappings: AttributeMappings, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttributeMappings>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.createMachineAccountMappingsV1(sourceId, attributeMappings, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MachineAccountMappingsApi.createMachineAccountMappingsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Use this API to remove machine account attribute mappings for a Source.  A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Delete source\'s machine account mappings
         * @param {string} sourceId source ID.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async deleteMachineAccountMappingsV1(sourceId: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteMachineAccountMappingsV1(sourceId, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MachineAccountMappingsApi.deleteMachineAccountMappingsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Retrieves Machine account mappings for a specified source using Source ID.
         * @summary Machine account mapping for source
         * @param {string} sourceId Source ID
         * @param {number} [limit] Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {number} [offset] Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async listMachineAccountMappingsV1(sourceId: string, limit?: number, offset?: number, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttributeMappings>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listMachineAccountMappingsV1(sourceId, limit, offset, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MachineAccountMappingsApi.listMachineAccountMappingsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Use this API to update Machine Account Attribute Mapping for a Source. A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Update source\'s machine account mappings
         * @param {string} sourceId Source ID.
         * @param {AttributeMappings} attributeMappings 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async setMachineAccountMappingsV1(sourceId: string, attributeMappings: AttributeMappings, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Array<AttributeMappings>>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setMachineAccountMappingsV1(sourceId, attributeMappings, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['MachineAccountMappingsApi.setMachineAccountMappingsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * MachineAccountMappingsApi - factory interface
 * @export
 */
export const MachineAccountMappingsApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = MachineAccountMappingsApiFp(configuration)
    return {
        /**
         * Creates Machine Account Mappings for both identities and accounts for a source. A token with API, ORG_ADMIN, ROLE_ADMIN, ROLE_SUBADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Create machine account mappings
         * @param {MachineAccountMappingsApiCreateMachineAccountMappingsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        createMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiCreateMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<AttributeMappings>> {
            return localVarFp.createMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.attributeMappings, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Use this API to remove machine account attribute mappings for a Source.  A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Delete source\'s machine account mappings
         * @param {MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        deleteMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteMachineAccountMappingsV1(requestParameters.sourceId, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Retrieves Machine account mappings for a specified source using Source ID.
         * @summary Machine account mapping for source
         * @param {MachineAccountMappingsApiListMachineAccountMappingsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        listMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiListMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<AttributeMappings>> {
            return localVarFp.listMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.limit, requestParameters.offset, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Use this API to update Machine Account Attribute Mapping for a Source. A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
         * @summary Update source\'s machine account mappings
         * @param {MachineAccountMappingsApiSetMachineAccountMappingsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        setMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiSetMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Array<AttributeMappings>> {
            return localVarFp.setMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.attributeMappings, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for createMachineAccountMappingsV1 operation in MachineAccountMappingsApi.
 * @export
 * @interface MachineAccountMappingsApiCreateMachineAccountMappingsV1Request
 */
export interface MachineAccountMappingsApiCreateMachineAccountMappingsV1Request {
    /**
     * Source ID.
     * @type {string}
     * @memberof MachineAccountMappingsApiCreateMachineAccountMappingsV1
     */
    readonly sourceId: string

    /**
     * 
     * @type {AttributeMappings}
     * @memberof MachineAccountMappingsApiCreateMachineAccountMappingsV1
     */
    readonly attributeMappings: AttributeMappings
}

/**
 * Request parameters for deleteMachineAccountMappingsV1 operation in MachineAccountMappingsApi.
 * @export
 * @interface MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request
 */
export interface MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request {
    /**
     * source ID.
     * @type {string}
     * @memberof MachineAccountMappingsApiDeleteMachineAccountMappingsV1
     */
    readonly sourceId: string
}

/**
 * Request parameters for listMachineAccountMappingsV1 operation in MachineAccountMappingsApi.
 * @export
 * @interface MachineAccountMappingsApiListMachineAccountMappingsV1Request
 */
export interface MachineAccountMappingsApiListMachineAccountMappingsV1Request {
    /**
     * Source ID
     * @type {string}
     * @memberof MachineAccountMappingsApiListMachineAccountMappingsV1
     */
    readonly sourceId: string

    /**
     * Max number of results to return. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof MachineAccountMappingsApiListMachineAccountMappingsV1
     */
    readonly limit?: number

    /**
     * Offset into the full result set. Usually specified with *limit* to paginate through the results. See [V3 API Standard Collection Parameters](https://developer.sailpoint.com/idn/api/standard-collection-parameters) for more information.
     * @type {number}
     * @memberof MachineAccountMappingsApiListMachineAccountMappingsV1
     */
    readonly offset?: number
}

/**
 * Request parameters for setMachineAccountMappingsV1 operation in MachineAccountMappingsApi.
 * @export
 * @interface MachineAccountMappingsApiSetMachineAccountMappingsV1Request
 */
export interface MachineAccountMappingsApiSetMachineAccountMappingsV1Request {
    /**
     * Source ID.
     * @type {string}
     * @memberof MachineAccountMappingsApiSetMachineAccountMappingsV1
     */
    readonly sourceId: string

    /**
     * 
     * @type {AttributeMappings}
     * @memberof MachineAccountMappingsApiSetMachineAccountMappingsV1
     */
    readonly attributeMappings: AttributeMappings
}

/**
 * MachineAccountMappingsApi - object-oriented interface
 * @export
 * @class MachineAccountMappingsApi
 * @extends {BaseAPI}
 */
export class MachineAccountMappingsApi extends BaseAPI {
    /**
     * Creates Machine Account Mappings for both identities and accounts for a source. A token with API, ORG_ADMIN, ROLE_ADMIN, ROLE_SUBADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
     * @summary Create machine account mappings
     * @param {MachineAccountMappingsApiCreateMachineAccountMappingsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof MachineAccountMappingsApi
     */
    public createMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiCreateMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return MachineAccountMappingsApiFp(this.configuration).createMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.attributeMappings, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this API to remove machine account attribute mappings for a Source.  A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
     * @summary Delete source\'s machine account mappings
     * @param {MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof MachineAccountMappingsApi
     */
    public deleteMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiDeleteMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return MachineAccountMappingsApiFp(this.configuration).deleteMachineAccountMappingsV1(requestParameters.sourceId, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Retrieves Machine account mappings for a specified source using Source ID.
     * @summary Machine account mapping for source
     * @param {MachineAccountMappingsApiListMachineAccountMappingsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof MachineAccountMappingsApi
     */
    public listMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiListMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return MachineAccountMappingsApiFp(this.configuration).listMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.limit, requestParameters.offset, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this API to update Machine Account Attribute Mapping for a Source. A token with ORG_ADMIN, SOURCE_ADMIN, or SOURCE_SUBADMIN authority is required to call this API.
     * @summary Update source\'s machine account mappings
     * @param {MachineAccountMappingsApiSetMachineAccountMappingsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof MachineAccountMappingsApi
     */
    public setMachineAccountMappingsV1(requestParameters: MachineAccountMappingsApiSetMachineAccountMappingsV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return MachineAccountMappingsApiFp(this.configuration).setMachineAccountMappingsV1(requestParameters.sourceId, requestParameters.attributeMappings, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



