- path: /password-org-config
  method: POST
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $passwordOrgConfigBeta = @"
        {customInstructionsEnabled=true, digitTokenEnabled=true, digitTokenDurationMinutes=12, digitTokenLength=9}
        "@
        
        # Create Password Org Config
        
        try {
            $Result = ConvertFrom-JsonTopasswordOrgConfigBeta -Json $passwordOrgConfigBeta
            -BetapasswordOrgConfigBeta $Result
            
            # Below is a request that includes all optional parameters
            #  -BetapasswordOrgConfigBeta $passwordOrgConfigBeta  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /password-org-config
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        
        # Get Password Org Config
        
        try {
            
            
            # Below is a request that includes all optional parameters
            #   
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /password-org-config
  method: PUT
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $passwordOrgConfigBeta = @"
        {digitTokenEnabled=true, digitTokenDurationMinutes=12}
        "@
        
        # Update Password Org Config
        
        try {
            $Result = ConvertFrom-JsonTopasswordOrgConfigBeta -Json $passwordOrgConfigBeta
            -BetapasswordOrgConfigBeta $Result
            
            # Below is a request that includes all optional parameters
            #  -BetapasswordOrgConfigBeta $passwordOrgConfigBeta  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
