- path: /sp-config/export
  method: POST
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $exportPayloadBeta = @"
        {description=Export all available objects, excludeTypes=[], includeTypes=[ACCESS_PROFILE, ACCESS_REQUEST_CONFIG, ATTR_SYNC_SOURCE_CONFIG, AUTH_ORG, CAMPAIGN_FILTER, FORM_DEFINITION, GOVERNANCE_GROUP, IDENTITY_OBJECT_CONFIG, IDENTITY_PROFILE, LIFECYCLE_STATE, NOTIFICATION_TEMPLATE, PASSWORD_POLICY, PASSWORD_SYNC_GROUP, PUBLIC_IDENTITIES_CONFIG, ROLE, RULE, SEGMENT, SERVICE_DESK_INTEGRATION, SOD_POLICY, SOURCE, TAG, TRANSFORM, TRIGGER_SUBSCRIPTION, WORKFLOW], objectOptions={}}
        "@
        
        # Initiates configuration objects export job
        
        try {
            $Result = ConvertFrom-JsonToexportPayloadBeta -Json $exportPayloadBeta
            -BetaexportPayloadBeta $Result
            
            # Below is a request that includes all optional parameters
            #  -BetaexportPayloadBeta $exportPayloadBeta  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/export/{id}/download
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $id =  # string | The ID of the export job whose results will be downloaded. (default to undefined)
        
        # Download export job result.
        
        try {
            -Betaid $id 
            
            # Below is a request that includes all optional parameters
            #  -Betaid $id  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/export/{id}
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $id =  # string | The ID of the export job whose status will be returned. (default to undefined)
        
        # Get export job status
        
        try {
            -Betaid $id 
            
            # Below is a request that includes all optional parameters
            #  -Betaid $id  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/import/{id}/download
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $id =  # string | The ID of the import job whose results will be downloaded. (default to undefined)
        
        # Download import job result
        
        try {
            -Betaid $id 
            
            # Below is a request that includes all optional parameters
            #  -Betaid $id  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/import/{id}
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $id =  # string | The ID of the import job whose status will be returned. (default to undefined)
        
        # Get import job status
        
        try {
            -Betaid $id 
            
            # Below is a request that includes all optional parameters
            #  -Betaid $id  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/import
  method: POST
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        $data =  # File | JSON file containing the objects to be imported. (default to undefined)
        $preview =  # boolean | This option is intended to give the user information about how an import operation would proceed, without having any effect on the target tenant. If this parameter is \"true\", no objects will be imported. Instead, the import process will pre-process the import file and attempt to resolve references within imported objects. The import result file will contain messages pertaining to how specific references were resolved, any errors associated with the preprocessing, and messages indicating which objects would be imported.  (optional) (default to false)
        $_options = @"
        "@
        
        # Initiates configuration objects import job
        
        try {
            -Betadata $data 
            
            # Below is a request that includes all optional parameters
            #  -Betadata $data -Betapreview $preview -Beta_options $_options  
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
- path: /sp-config/config-objects
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        
        # Get config object details
        
        try {
            
            
            # Below is a request that includes all optional parameters
            #   
        } catch {
            Write-Host $_.Exception.Response.StatusCode.value__ "Exception occurred when calling "
            Write-Host $_.ErrorDetails
        }
