/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Public Identities Config
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * An enumeration of the types of DTOs supported within the IdentityNow infrastructure.
 * @export
 * @enum {string}
 */

export const DtotypeV1 = {
    AccountCorrelationConfig: 'ACCOUNT_CORRELATION_CONFIG',
    AccessProfile: 'ACCESS_PROFILE',
    AccessRequestApproval: 'ACCESS_REQUEST_APPROVAL',
    Account: 'ACCOUNT',
    Application: 'APPLICATION',
    Campaign: 'CAMPAIGN',
    CampaignFilter: 'CAMPAIGN_FILTER',
    Certification: 'CERTIFICATION',
    Cluster: 'CLUSTER',
    ConnectorSchema: 'CONNECTOR_SCHEMA',
    Entitlement: 'ENTITLEMENT',
    GovernanceGroup: 'GOVERNANCE_GROUP',
    Identity: 'IDENTITY',
    IdentityProfile: 'IDENTITY_PROFILE',
    IdentityRequest: 'IDENTITY_REQUEST',
    MachineIdentity: 'MACHINE_IDENTITY',
    LifecycleState: 'LIFECYCLE_STATE',
    PasswordPolicy: 'PASSWORD_POLICY',
    Role: 'ROLE',
    Rule: 'RULE',
    SodPolicy: 'SOD_POLICY',
    Source: 'SOURCE',
    Tag: 'TAG',
    TagCategory: 'TAG_CATEGORY',
    TaskResult: 'TASK_RESULT',
    ReportResult: 'REPORT_RESULT',
    SodViolation: 'SOD_VIOLATION',
    AccountActivity: 'ACCOUNT_ACTIVITY',
    Workgroup: 'WORKGROUP'
} as const;

export type DtotypeV1 = typeof DtotypeV1[keyof typeof DtotypeV1];


/**
 * 
 * @export
 * @interface ErrormessagedtoV1
 */
export interface ErrormessagedtoV1 {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleoriginV1}
     * @memberof ErrormessagedtoV1
     */
    'localeOrigin'?: LocaleoriginV1 | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorresponsedtoV1
 */
export interface ErrorresponsedtoV1 {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'messages'?: Array<ErrormessagedtoV1>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'causes'?: Array<ErrormessagedtoV1>;
}
/**
 * 
 * @export
 * @interface GetPublicIdentityConfigV1401ResponseV1
 */
export interface GetPublicIdentityConfigV1401ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetPublicIdentityConfigV1401ResponseV1
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface GetPublicIdentityConfigV1429ResponseV1
 */
export interface GetPublicIdentityConfigV1429ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetPublicIdentityConfigV1429ResponseV1
     */
    'message'?: any;
}
/**
 * The manager for the identity.
 * @export
 * @interface IdentityreferenceV1
 */
export interface IdentityreferenceV1 {
    /**
     * 
     * @type {DtotypeV1}
     * @memberof IdentityreferenceV1
     */
    'type'?: DtotypeV1;
    /**
     * Identity id
     * @type {string}
     * @memberof IdentityreferenceV1
     */
    'id'?: string;
    /**
     * Human-readable display name of identity.
     * @type {string}
     * @memberof IdentityreferenceV1
     */
    'name'?: string;
}


/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleoriginV1 = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleoriginV1 = typeof LocaleoriginV1[keyof typeof LocaleoriginV1];


/**
 * Used to map an attribute key for an Identity to its display name.
 * @export
 * @interface PublicidentityattributeconfigV1
 */
export interface PublicidentityattributeconfigV1 {
    /**
     * The attribute key
     * @type {string}
     * @memberof PublicidentityattributeconfigV1
     */
    'key'?: string;
    /**
     * The attribute display name
     * @type {string}
     * @memberof PublicidentityattributeconfigV1
     */
    'name'?: string;
}
/**
 * Details of up to 5 Identity attributes that will be publicly accessible for all Identities to anyone in the org.
 * @export
 * @interface PublicidentityconfigV1
 */
export interface PublicidentityconfigV1 {
    /**
     * Up to 5 identity attributes that will be available to everyone in the org for all users in the org.
     * @type {Array<PublicidentityattributeconfigV1>}
     * @memberof PublicidentityconfigV1
     */
    'attributes'?: Array<PublicidentityattributeconfigV1>;
    /**
     * When this configuration was last modified.
     * @type {string}
     * @memberof PublicidentityconfigV1
     */
    'modified'?: string | null;
    /**
     * 
     * @type {IdentityreferenceV1}
     * @memberof PublicidentityconfigV1
     */
    'modifiedBy'?: IdentityreferenceV1 | null;
}

/**
 * PublicIdentitiesConfigV1Api - axios parameter creator
 * @export
 */
export const PublicIdentitiesConfigV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Returns the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Get the public identities configuration
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getPublicIdentityConfigV1: async (axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/public-identities-config/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Updates the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Update the public identities configuration
         * @param {PublicidentityconfigV1} publicidentityconfigV1 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updatePublicIdentityConfigV1: async (publicidentityconfigV1: PublicidentityconfigV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'publicidentityconfigV1' is not null or undefined
            assertParamExists('updatePublicIdentityConfigV1', 'publicidentityconfigV1', publicidentityconfigV1)
            const localVarPath = `/public-identities-config/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(publicidentityconfigV1, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * PublicIdentitiesConfigV1Api - functional programming interface
 * @export
 */
export const PublicIdentitiesConfigV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PublicIdentitiesConfigV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * Returns the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Get the public identities configuration
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getPublicIdentityConfigV1(axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicidentityconfigV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getPublicIdentityConfigV1(axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicIdentitiesConfigV1Api.getPublicIdentityConfigV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Updates the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Update the public identities configuration
         * @param {PublicidentityconfigV1} publicidentityconfigV1 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async updatePublicIdentityConfigV1(publicidentityconfigV1: PublicidentityconfigV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PublicidentityconfigV1>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updatePublicIdentityConfigV1(publicidentityconfigV1, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['PublicIdentitiesConfigV1Api.updatePublicIdentityConfigV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * PublicIdentitiesConfigV1Api - factory interface
 * @export
 */
export const PublicIdentitiesConfigV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PublicIdentitiesConfigV1ApiFp(configuration)
    return {
        /**
         * Returns the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Get the public identities configuration
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getPublicIdentityConfigV1(axiosOptions?: RawAxiosRequestConfig): AxiosPromise<PublicidentityconfigV1> {
            return localVarFp.getPublicIdentityConfigV1(axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Updates the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
         * @summary Update the public identities configuration
         * @param {PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        updatePublicIdentityConfigV1(requestParameters: PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<PublicidentityconfigV1> {
            return localVarFp.updatePublicIdentityConfigV1(requestParameters.publicidentityconfigV1, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for updatePublicIdentityConfigV1 operation in PublicIdentitiesConfigV1Api.
 * @export
 * @interface PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request
 */
export interface PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request {
    /**
     * 
     * @type {PublicidentityconfigV1}
     * @memberof PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1
     */
    readonly publicidentityconfigV1: PublicidentityconfigV1
}

/**
 * PublicIdentitiesConfigV1Api - object-oriented interface
 * @export
 * @class PublicIdentitiesConfigV1Api
 * @extends {BaseAPI}
 */
export class PublicIdentitiesConfigV1Api extends BaseAPI {
    /**
     * Returns the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
     * @summary Get the public identities configuration
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicIdentitiesConfigV1Api
     */
    public getPublicIdentityConfigV1(axiosOptions?: RawAxiosRequestConfig) {
        return PublicIdentitiesConfigV1ApiFp(this.configuration).getPublicIdentityConfigV1(axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Updates the publicly visible attributes of an identity available to request approvers for Access Requests and Certification Campaigns.
     * @summary Update the public identities configuration
     * @param {PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof PublicIdentitiesConfigV1Api
     */
    public updatePublicIdentityConfigV1(requestParameters: PublicIdentitiesConfigV1ApiUpdatePublicIdentityConfigV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return PublicIdentitiesConfigV1ApiFp(this.configuration).updatePublicIdentityConfigV1(requestParameters.publicidentityconfigV1, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



