/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Reports Data Extraction
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * Arguments for Account Export report (ACCOUNTS)
 * @export
 * @interface AccountsExportReportArguments
 */
export interface AccountsExportReportArguments {
    /**
     * Source ID.
     * @type {string}
     * @memberof AccountsExportReportArguments
     */
    'application': string;
    /**
     * Source name.
     * @type {string}
     * @memberof AccountsExportReportArguments
     */
    'sourceName': string;
}
/**
 * 
 * @export
 * @interface Errormessagedto
 */
export interface Errormessagedto {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof Errormessagedto
     */
    'locale'?: string | null;
    /**
     * 
     * @type {Localeorigin}
     * @memberof Errormessagedto
     */
    'localeOrigin'?: Localeorigin | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof Errormessagedto
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface Errorresponsedto
 */
export interface Errorresponsedto {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof Errorresponsedto
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof Errorresponsedto
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<Errormessagedto>}
     * @memberof Errorresponsedto
     */
    'messages'?: Array<Errormessagedto>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<Errormessagedto>}
     * @memberof Errorresponsedto
     */
    'causes'?: Array<Errormessagedto>;
}
/**
 * 
 * @export
 * @interface GetReportResultV1401Response
 */
export interface GetReportResultV1401Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetReportResultV1401Response
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface GetReportResultV1429Response
 */
export interface GetReportResultV1429Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetReportResultV1429Response
     */
    'message'?: any;
}
/**
 * Arguments for Identities Details report (IDENTITIES_DETAILS)
 * @export
 * @interface IdentitiesDetailsReportArguments
 */
export interface IdentitiesDetailsReportArguments {
    /**
     * Flag to specify if only correlated identities are included in report.
     * @type {boolean}
     * @memberof IdentitiesDetailsReportArguments
     */
    'correlatedOnly': boolean;
}
/**
 * Arguments for Identities report (IDENTITIES)
 * @export
 * @interface IdentitiesReportArguments
 */
export interface IdentitiesReportArguments {
    /**
     * Flag to specify if only correlated identities are included in report.
     * @type {boolean}
     * @memberof IdentitiesReportArguments
     */
    'correlatedOnly'?: boolean;
}
/**
 * Arguments for Identity Profile Identity Error report (IDENTITY_PROFILE_IDENTITY_ERROR)
 * @export
 * @interface IdentityProfileIdentityErrorReportArguments
 */
export interface IdentityProfileIdentityErrorReportArguments {
    /**
     * Source ID.
     * @type {string}
     * @memberof IdentityProfileIdentityErrorReportArguments
     */
    'authoritativeSource': string;
}
/**
 * Enum representing the currently supported indices. Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const Index = {
    Accessprofiles: 'accessprofiles',
    Accountactivities: 'accountactivities',
    Entitlements: 'entitlements',
    Events: 'events',
    Identities: 'identities',
    Roles: 'roles',
    Star: '*'
} as const;

export type Index = typeof Index[keyof typeof Index];


/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const Localeorigin = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type Localeorigin = typeof Localeorigin[keyof typeof Localeorigin];


/**
 * Arguments for Orphan Identities report (ORPHAN_IDENTITIES)
 * @export
 * @interface OrphanIdentitiesReportArguments
 */
export interface OrphanIdentitiesReportArguments {
    /**
     * Output report file formats. These are formats for calling GET endpoint as query parameter \'fileFormat\'.  In case report won\'t have this argument there will be [\'CSV\', \'PDF\'] as default.
     * @type {Array<string>}
     * @memberof OrphanIdentitiesReportArguments
     */
    'selectedFormats'?: Array<OrphanIdentitiesReportArgumentsSelectedFormatsEnum>;
}

export const OrphanIdentitiesReportArgumentsSelectedFormatsEnum = {
    Csv: 'CSV',
    Pdf: 'PDF'
} as const;

export type OrphanIdentitiesReportArgumentsSelectedFormatsEnum = typeof OrphanIdentitiesReportArgumentsSelectedFormatsEnum[keyof typeof OrphanIdentitiesReportArgumentsSelectedFormatsEnum];

/**
 * Details about report to be processed.
 * @export
 * @interface Reportdetails
 */
export interface Reportdetails {
    /**
     * Use this property to define what report should be processed in the RDE service.
     * @type {string}
     * @memberof Reportdetails
     */
    'reportType'?: ReportdetailsReportTypeEnum;
    /**
     * 
     * @type {ReportdetailsArguments}
     * @memberof Reportdetails
     */
    'arguments'?: ReportdetailsArguments;
}

export const ReportdetailsReportTypeEnum = {
    Accounts: 'ACCOUNTS',
    IdentitiesDetails: 'IDENTITIES_DETAILS',
    Identities: 'IDENTITIES',
    IdentityProfileIdentityError: 'IDENTITY_PROFILE_IDENTITY_ERROR',
    OrphanIdentities: 'ORPHAN_IDENTITIES',
    SearchExport: 'SEARCH_EXPORT',
    UncorrelatedAccounts: 'UNCORRELATED_ACCOUNTS'
} as const;

export type ReportdetailsReportTypeEnum = typeof ReportdetailsReportTypeEnum[keyof typeof ReportdetailsReportTypeEnum];

/**
 * The string-object map(dictionary) with the arguments needed for report processing.
 * @export
 * @interface ReportdetailsArguments
 */
export interface ReportdetailsArguments {
    /**
     * Source ID.
     * @type {string}
     * @memberof ReportdetailsArguments
     */
    'application': string;
    /**
     * Source name.
     * @type {string}
     * @memberof ReportdetailsArguments
     */
    'sourceName': string;
    /**
     * Flag to specify if only correlated identities are included in report.
     * @type {boolean}
     * @memberof ReportdetailsArguments
     */
    'correlatedOnly': boolean;
    /**
     * Source ID.
     * @type {string}
     * @memberof ReportdetailsArguments
     */
    'authoritativeSource': string;
    /**
     * Output report file formats. These are formats for calling GET endpoint as query parameter \'fileFormat\'.  In case report won\'t have this argument there will be [\'CSV\', \'PDF\'] as default.
     * @type {Array<string>}
     * @memberof ReportdetailsArguments
     */
    'selectedFormats'?: Array<ReportdetailsArgumentsSelectedFormatsEnum>;
    /**
     * The names of the Elasticsearch indices in which to search. If none are provided, then all indices will be searched.
     * @type {Array<Index>}
     * @memberof ReportdetailsArguments
     */
    'indices'?: Array<Index>;
    /**
     * The query using the Elasticsearch [Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-query-string-query.html#query-string) syntax from the Query DSL extended by SailPoint to support Nested queries.
     * @type {string}
     * @memberof ReportdetailsArguments
     */
    'query': string;
    /**
     * Comma separated string consisting of technical attribute names of fields to include in report.  Use `access.spread`, `apps.spread`, `accounts.spread` to include respective identity access details.  Use `accessProfiles.spread` to unclude access profile details.  Use `entitlements.spread` to include entitlement details. 
     * @type {string}
     * @memberof ReportdetailsArguments
     */
    'columns'?: string;
    /**
     * The fields to be used to sort the search results. Use + or - to specify the sort direction.
     * @type {Array<string>}
     * @memberof ReportdetailsArguments
     */
    'sort'?: Array<string>;
}

export const ReportdetailsArgumentsSelectedFormatsEnum = {
    Csv: 'CSV',
    Pdf: 'PDF'
} as const;

export type ReportdetailsArgumentsSelectedFormatsEnum = typeof ReportdetailsArgumentsSelectedFormatsEnum[keyof typeof ReportdetailsArgumentsSelectedFormatsEnum];

/**
 * Details about report result or current state.
 * @export
 * @interface Reportresults
 */
export interface Reportresults {
    /**
     * Use this property to define what report should be processed in the RDE service.
     * @type {string}
     * @memberof Reportresults
     */
    'reportType'?: ReportresultsReportTypeEnum;
    /**
     * Name of the task definition which is started to process requesting report. Usually the same as report name
     * @type {string}
     * @memberof Reportresults
     */
    'taskDefName'?: string;
    /**
     * Unique task definition identifier.
     * @type {string}
     * @memberof Reportresults
     */
    'id'?: string;
    /**
     * Report processing start date
     * @type {string}
     * @memberof Reportresults
     */
    'created'?: string;
    /**
     * Report current state or result status.
     * @type {string}
     * @memberof Reportresults
     */
    'status'?: ReportresultsStatusEnum;
    /**
     * Report processing time in ms.
     * @type {number}
     * @memberof Reportresults
     */
    'duration'?: number;
    /**
     * Report size in rows.
     * @type {number}
     * @memberof Reportresults
     */
    'rows'?: number;
    /**
     * Output report file formats. This are formats for calling get endpoint as a query parameter \'fileFormat\'.  In case report won\'t have this argument there will be [\'CSV\', \'PDF\'] as default.
     * @type {Array<string>}
     * @memberof Reportresults
     */
    'availableFormats'?: Array<ReportresultsAvailableFormatsEnum>;
}

export const ReportresultsReportTypeEnum = {
    Accounts: 'ACCOUNTS',
    IdentitiesDetails: 'IDENTITIES_DETAILS',
    Identities: 'IDENTITIES',
    IdentityProfileIdentityError: 'IDENTITY_PROFILE_IDENTITY_ERROR',
    OrphanIdentities: 'ORPHAN_IDENTITIES',
    SearchExport: 'SEARCH_EXPORT',
    UncorrelatedAccounts: 'UNCORRELATED_ACCOUNTS'
} as const;

export type ReportresultsReportTypeEnum = typeof ReportresultsReportTypeEnum[keyof typeof ReportresultsReportTypeEnum];
export const ReportresultsStatusEnum = {
    Success: 'SUCCESS',
    Failure: 'FAILURE',
    Warning: 'WARNING',
    Terminated: 'TERMINATED'
} as const;

export type ReportresultsStatusEnum = typeof ReportresultsStatusEnum[keyof typeof ReportresultsStatusEnum];
export const ReportresultsAvailableFormatsEnum = {
    Csv: 'CSV',
    Pdf: 'PDF'
} as const;

export type ReportresultsAvailableFormatsEnum = typeof ReportresultsAvailableFormatsEnum[keyof typeof ReportresultsAvailableFormatsEnum];

/**
 * Arguments for Search Export report (SEARCH_EXPORT)  The report file generated will be a zip file containing csv files of the search results. 
 * @export
 * @interface SearchExportReportArguments
 */
export interface SearchExportReportArguments {
    /**
     * The names of the Elasticsearch indices in which to search. If none are provided, then all indices will be searched.
     * @type {Array<Index>}
     * @memberof SearchExportReportArguments
     */
    'indices'?: Array<Index>;
    /**
     * The query using the Elasticsearch [Query String Query](https://www.elastic.co/guide/en/elasticsearch/reference/5.2/query-dsl-query-string-query.html#query-string) syntax from the Query DSL extended by SailPoint to support Nested queries.
     * @type {string}
     * @memberof SearchExportReportArguments
     */
    'query': string;
    /**
     * Comma separated string consisting of technical attribute names of fields to include in report.  Use `access.spread`, `apps.spread`, `accounts.spread` to include respective identity access details.  Use `accessProfiles.spread` to unclude access profile details.  Use `entitlements.spread` to include entitlement details. 
     * @type {string}
     * @memberof SearchExportReportArguments
     */
    'columns'?: string;
    /**
     * The fields to be used to sort the search results. Use + or - to specify the sort direction.
     * @type {Array<string>}
     * @memberof SearchExportReportArguments
     */
    'sort'?: Array<string>;
}
/**
 * Details about job or task type, state and lifecycle.
 * @export
 * @interface Taskresultdetails
 */
export interface Taskresultdetails {
    /**
     * Type of the job or task underlying in the report processing. It could be a quartz task, QPOC or MENTOS jobs or a refresh/sync task.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'type'?: TaskresultdetailsTypeEnum;
    /**
     * Unique task definition identifier.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'id'?: string;
    /**
     * Use this property to define what report should be processed in the RDE service.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'reportType'?: TaskresultdetailsReportTypeEnum;
    /**
     * Description of the report purpose and/or contents.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'description'?: string;
    /**
     * Name of the parent task/report if exists.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'parentName'?: string | null;
    /**
     * Name of the report processing initiator.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'launcher'?: string;
    /**
     * Report creation date
     * @type {string}
     * @memberof Taskresultdetails
     */
    'created'?: string;
    /**
     * Report start date
     * @type {string}
     * @memberof Taskresultdetails
     */
    'launched'?: string | null;
    /**
     * Report completion date
     * @type {string}
     * @memberof Taskresultdetails
     */
    'completed'?: string | null;
    /**
     * Report completion status.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'completionStatus'?: TaskresultdetailsCompletionStatusEnum | null;
    /**
     * List of the messages dedicated to the report.  From task definition perspective here usually should be warnings or errors.
     * @type {Array<TaskresultdetailsMessagesInner>}
     * @memberof Taskresultdetails
     */
    'messages'?: Array<TaskresultdetailsMessagesInner>;
    /**
     * Task definition results, if necessary.
     * @type {Array<TaskresultdetailsReturnsInner>}
     * @memberof Taskresultdetails
     */
    'returns'?: Array<TaskresultdetailsReturnsInner>;
    /**
     * Extra attributes map(dictionary) needed for the report.
     * @type {object}
     * @memberof Taskresultdetails
     */
    'attributes'?: object;
    /**
     * Current report state.
     * @type {string}
     * @memberof Taskresultdetails
     */
    'progress'?: string | null;
}

export const TaskresultdetailsTypeEnum = {
    Quartz: 'QUARTZ',
    Qpoc: 'QPOC',
    Mentos: 'MENTOS',
    QueuedTask: 'QUEUED_TASK'
} as const;

export type TaskresultdetailsTypeEnum = typeof TaskresultdetailsTypeEnum[keyof typeof TaskresultdetailsTypeEnum];
export const TaskresultdetailsReportTypeEnum = {
    Accounts: 'ACCOUNTS',
    IdentitiesDetails: 'IDENTITIES_DETAILS',
    Identities: 'IDENTITIES',
    IdentityProfileIdentityError: 'IDENTITY_PROFILE_IDENTITY_ERROR',
    OrphanIdentities: 'ORPHAN_IDENTITIES',
    SearchExport: 'SEARCH_EXPORT',
    UncorrelatedAccounts: 'UNCORRELATED_ACCOUNTS'
} as const;

export type TaskresultdetailsReportTypeEnum = typeof TaskresultdetailsReportTypeEnum[keyof typeof TaskresultdetailsReportTypeEnum];
export const TaskresultdetailsCompletionStatusEnum = {
    Success: 'SUCCESS',
    Warning: 'WARNING',
    Error: 'ERROR',
    Terminated: 'TERMINATED',
    TempError: 'TEMP_ERROR'
} as const;

export type TaskresultdetailsCompletionStatusEnum = typeof TaskresultdetailsCompletionStatusEnum[keyof typeof TaskresultdetailsCompletionStatusEnum];

/**
 * 
 * @export
 * @interface TaskresultdetailsMessagesInner
 */
export interface TaskresultdetailsMessagesInner {
    /**
     * Type of the message.
     * @type {string}
     * @memberof TaskresultdetailsMessagesInner
     */
    'type'?: TaskresultdetailsMessagesInnerTypeEnum;
    /**
     * Flag whether message is an error.
     * @type {boolean}
     * @memberof TaskresultdetailsMessagesInner
     */
    'error'?: boolean;
    /**
     * Flag whether message is a warning.
     * @type {boolean}
     * @memberof TaskresultdetailsMessagesInner
     */
    'warning'?: boolean;
    /**
     * Message string identifier.
     * @type {string}
     * @memberof TaskresultdetailsMessagesInner
     */
    'key'?: string;
    /**
     * Message context with the locale based language.
     * @type {string}
     * @memberof TaskresultdetailsMessagesInner
     */
    'localizedText'?: string;
}

export const TaskresultdetailsMessagesInnerTypeEnum = {
    Info: 'INFO',
    Warn: 'WARN',
    Error: 'ERROR'
} as const;

export type TaskresultdetailsMessagesInnerTypeEnum = typeof TaskresultdetailsMessagesInnerTypeEnum[keyof typeof TaskresultdetailsMessagesInnerTypeEnum];

/**
 * 
 * @export
 * @interface TaskresultdetailsReturnsInner
 */
export interface TaskresultdetailsReturnsInner {
    /**
     * Attribute description.
     * @type {string}
     * @memberof TaskresultdetailsReturnsInner
     */
    'displayLabel'?: string;
    /**
     * System or database attribute name.
     * @type {string}
     * @memberof TaskresultdetailsReturnsInner
     */
    'attributeName'?: string;
}
/**
 * Arguments for Uncorrelated Accounts report (UNCORRELATED_ACCOUNTS)
 * @export
 * @interface UncorrelatedAccountsReportArguments
 */
export interface UncorrelatedAccountsReportArguments {
    /**
     * Output report file formats. These are formats for calling GET endpoint as query parameter \'fileFormat\'.  In case report won\'t have this argument there will be [\'CSV\', \'PDF\'] as default.
     * @type {Array<string>}
     * @memberof UncorrelatedAccountsReportArguments
     */
    'selectedFormats'?: Array<UncorrelatedAccountsReportArgumentsSelectedFormatsEnum>;
}

export const UncorrelatedAccountsReportArgumentsSelectedFormatsEnum = {
    Csv: 'CSV',
    Pdf: 'PDF'
} as const;

export type UncorrelatedAccountsReportArgumentsSelectedFormatsEnum = typeof UncorrelatedAccountsReportArgumentsSelectedFormatsEnum[keyof typeof UncorrelatedAccountsReportArgumentsSelectedFormatsEnum];


/**
 * ReportsDataExtractionApi - axios parameter creator
 * @export
 */
export const ReportsDataExtractionApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Cancels a running report.
         * @summary Cancel report
         * @param {string} id ID of the running Report to cancel
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        cancelReportV1: async (id: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'id' is not null or undefined
            assertParamExists('cancelReportV1', 'id', id)
            const localVarPath = `/reports/v1/{id}/cancel`
                .replace(`{${"id"}}`, encodeURIComponent(String(id)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Get the report results for a report that was run or is running. Returns empty report result in case there are no active task definitions with used in payload task definition name.
         * @summary Get report result
         * @param {string} taskResultId Unique identifier of the task result which handled report
         * @param {boolean} [completed] state of task result to apply ordering when results are fetching from the DB
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getReportResultV1: async (taskResultId: string, completed?: boolean, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskResultId' is not null or undefined
            assertParamExists('getReportResultV1', 'taskResultId', taskResultId)
            const localVarPath = `/reports/v1/{taskResultId}/result`
                .replace(`{${"taskResultId"}}`, encodeURIComponent(String(taskResultId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (completed !== undefined) {
                localVarQueryParameter['completed'] = completed;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Gets a report in file format.
         * @summary Get report file
         * @param {string} taskResultId Unique identifier of the task result which handled report
         * @param {GetReportV1FileFormatEnum} fileFormat Output format of the requested report file
         * @param {string} [name] preferred Report file name, by default will be used report name from task result.
         * @param {boolean} [auditable] Enables auditing for current report download. Will create an audit event and sent it to the REPORT cloud-audit kafka topic.  Event will be created if there is any result present by requested taskResultId.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getReportV1: async (taskResultId: string, fileFormat: GetReportV1FileFormatEnum, name?: string, auditable?: boolean, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'taskResultId' is not null or undefined
            assertParamExists('getReportV1', 'taskResultId', taskResultId)
            // verify required parameter 'fileFormat' is not null or undefined
            assertParamExists('getReportV1', 'fileFormat', fileFormat)
            const localVarPath = `/reports/v1/{taskResultId}`
                .replace(`{${"taskResultId"}}`, encodeURIComponent(String(taskResultId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (fileFormat !== undefined) {
                localVarQueryParameter['fileFormat'] = fileFormat;
            }

            if (name !== undefined) {
                localVarQueryParameter['name'] = name;
            }

            if (auditable !== undefined) {
                localVarQueryParameter['auditable'] = auditable;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * Use this API to run a report according to report input details. If non-concurrent task is already running then it returns, otherwise new task creates and returns.
         * @summary Run report
         * @param {Reportdetails} reportdetails 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        startReportV1: async (reportdetails: Reportdetails, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'reportdetails' is not null or undefined
            assertParamExists('startReportV1', 'reportdetails', reportdetails)
            const localVarPath = `/reports/v1/run`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(reportdetails, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * ReportsDataExtractionApi - functional programming interface
 * @export
 */
export const ReportsDataExtractionApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = ReportsDataExtractionApiAxiosParamCreator(configuration)
    return {
        /**
         * Cancels a running report.
         * @summary Cancel report
         * @param {string} id ID of the running Report to cancel
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async cancelReportV1(id: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelReportV1(id, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportsDataExtractionApi.cancelReportV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Get the report results for a report that was run or is running. Returns empty report result in case there are no active task definitions with used in payload task definition name.
         * @summary Get report result
         * @param {string} taskResultId Unique identifier of the task result which handled report
         * @param {boolean} [completed] state of task result to apply ordering when results are fetching from the DB
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getReportResultV1(taskResultId: string, completed?: boolean, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Reportresults>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReportResultV1(taskResultId, completed, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportsDataExtractionApi.getReportResultV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Gets a report in file format.
         * @summary Get report file
         * @param {string} taskResultId Unique identifier of the task result which handled report
         * @param {GetReportV1FileFormatEnum} fileFormat Output format of the requested report file
         * @param {string} [name] preferred Report file name, by default will be used report name from task result.
         * @param {boolean} [auditable] Enables auditing for current report download. Will create an audit event and sent it to the REPORT cloud-audit kafka topic.  Event will be created if there is any result present by requested taskResultId.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getReportV1(taskResultId: string, fileFormat: GetReportV1FileFormatEnum, name?: string, auditable?: boolean, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<File>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getReportV1(taskResultId, fileFormat, name, auditable, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportsDataExtractionApi.getReportV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * Use this API to run a report according to report input details. If non-concurrent task is already running then it returns, otherwise new task creates and returns.
         * @summary Run report
         * @param {Reportdetails} reportdetails 
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async startReportV1(reportdetails: Reportdetails, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Taskresultdetails>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startReportV1(reportdetails, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['ReportsDataExtractionApi.startReportV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * ReportsDataExtractionApi - factory interface
 * @export
 */
export const ReportsDataExtractionApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = ReportsDataExtractionApiFp(configuration)
    return {
        /**
         * Cancels a running report.
         * @summary Cancel report
         * @param {ReportsDataExtractionApiCancelReportV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        cancelReportV1(requestParameters: ReportsDataExtractionApiCancelReportV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cancelReportV1(requestParameters.id, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Get the report results for a report that was run or is running. Returns empty report result in case there are no active task definitions with used in payload task definition name.
         * @summary Get report result
         * @param {ReportsDataExtractionApiGetReportResultV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getReportResultV1(requestParameters: ReportsDataExtractionApiGetReportResultV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Reportresults> {
            return localVarFp.getReportResultV1(requestParameters.taskResultId, requestParameters.completed, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Gets a report in file format.
         * @summary Get report file
         * @param {ReportsDataExtractionApiGetReportV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getReportV1(requestParameters: ReportsDataExtractionApiGetReportV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<File> {
            return localVarFp.getReportV1(requestParameters.taskResultId, requestParameters.fileFormat, requestParameters.name, requestParameters.auditable, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * Use this API to run a report according to report input details. If non-concurrent task is already running then it returns, otherwise new task creates and returns.
         * @summary Run report
         * @param {ReportsDataExtractionApiStartReportV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        startReportV1(requestParameters: ReportsDataExtractionApiStartReportV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Taskresultdetails> {
            return localVarFp.startReportV1(requestParameters.reportdetails, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cancelReportV1 operation in ReportsDataExtractionApi.
 * @export
 * @interface ReportsDataExtractionApiCancelReportV1Request
 */
export interface ReportsDataExtractionApiCancelReportV1Request {
    /**
     * ID of the running Report to cancel
     * @type {string}
     * @memberof ReportsDataExtractionApiCancelReportV1
     */
    readonly id: string
}

/**
 * Request parameters for getReportResultV1 operation in ReportsDataExtractionApi.
 * @export
 * @interface ReportsDataExtractionApiGetReportResultV1Request
 */
export interface ReportsDataExtractionApiGetReportResultV1Request {
    /**
     * Unique identifier of the task result which handled report
     * @type {string}
     * @memberof ReportsDataExtractionApiGetReportResultV1
     */
    readonly taskResultId: string

    /**
     * state of task result to apply ordering when results are fetching from the DB
     * @type {boolean}
     * @memberof ReportsDataExtractionApiGetReportResultV1
     */
    readonly completed?: boolean
}

/**
 * Request parameters for getReportV1 operation in ReportsDataExtractionApi.
 * @export
 * @interface ReportsDataExtractionApiGetReportV1Request
 */
export interface ReportsDataExtractionApiGetReportV1Request {
    /**
     * Unique identifier of the task result which handled report
     * @type {string}
     * @memberof ReportsDataExtractionApiGetReportV1
     */
    readonly taskResultId: string

    /**
     * Output format of the requested report file
     * @type {'csv' | 'pdf'}
     * @memberof ReportsDataExtractionApiGetReportV1
     */
    readonly fileFormat: GetReportV1FileFormatEnum

    /**
     * preferred Report file name, by default will be used report name from task result.
     * @type {string}
     * @memberof ReportsDataExtractionApiGetReportV1
     */
    readonly name?: string

    /**
     * Enables auditing for current report download. Will create an audit event and sent it to the REPORT cloud-audit kafka topic.  Event will be created if there is any result present by requested taskResultId.
     * @type {boolean}
     * @memberof ReportsDataExtractionApiGetReportV1
     */
    readonly auditable?: boolean
}

/**
 * Request parameters for startReportV1 operation in ReportsDataExtractionApi.
 * @export
 * @interface ReportsDataExtractionApiStartReportV1Request
 */
export interface ReportsDataExtractionApiStartReportV1Request {
    /**
     * 
     * @type {Reportdetails}
     * @memberof ReportsDataExtractionApiStartReportV1
     */
    readonly reportdetails: Reportdetails
}

/**
 * ReportsDataExtractionApi - object-oriented interface
 * @export
 * @class ReportsDataExtractionApi
 * @extends {BaseAPI}
 */
export class ReportsDataExtractionApi extends BaseAPI {
    /**
     * Cancels a running report.
     * @summary Cancel report
     * @param {ReportsDataExtractionApiCancelReportV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsDataExtractionApi
     */
    public cancelReportV1(requestParameters: ReportsDataExtractionApiCancelReportV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ReportsDataExtractionApiFp(this.configuration).cancelReportV1(requestParameters.id, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Get the report results for a report that was run or is running. Returns empty report result in case there are no active task definitions with used in payload task definition name.
     * @summary Get report result
     * @param {ReportsDataExtractionApiGetReportResultV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsDataExtractionApi
     */
    public getReportResultV1(requestParameters: ReportsDataExtractionApiGetReportResultV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ReportsDataExtractionApiFp(this.configuration).getReportResultV1(requestParameters.taskResultId, requestParameters.completed, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Gets a report in file format.
     * @summary Get report file
     * @param {ReportsDataExtractionApiGetReportV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsDataExtractionApi
     */
    public getReportV1(requestParameters: ReportsDataExtractionApiGetReportV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ReportsDataExtractionApiFp(this.configuration).getReportV1(requestParameters.taskResultId, requestParameters.fileFormat, requestParameters.name, requestParameters.auditable, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Use this API to run a report according to report input details. If non-concurrent task is already running then it returns, otherwise new task creates and returns.
     * @summary Run report
     * @param {ReportsDataExtractionApiStartReportV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof ReportsDataExtractionApi
     */
    public startReportV1(requestParameters: ReportsDataExtractionApiStartReportV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return ReportsDataExtractionApiFp(this.configuration).startReportV1(requestParameters.reportdetails, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetReportV1FileFormatEnum = {
    Csv: 'csv',
    Pdf: 'pdf'
} as const;
export type GetReportV1FileFormatEnum = typeof GetReportV1FileFormatEnum[keyof typeof GetReportV1FileFormatEnum];


