/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Access Request Identity Metrics
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrormessagedtoV1
 */
export interface ErrormessagedtoV1 {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleoriginV1}
     * @memberof ErrormessagedtoV1
     */
    'localeOrigin'?: LocaleoriginV1 | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrormessagedtoV1
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorresponsedtoV1
 */
export interface ErrorresponsedtoV1 {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorresponsedtoV1
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'messages'?: Array<ErrormessagedtoV1>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrormessagedtoV1>}
     * @memberof ErrorresponsedtoV1
     */
    'causes'?: Array<ErrormessagedtoV1>;
}
/**
 * 
 * @export
 * @interface GetAccessRequestIdentityMetricsV1401ResponseV1
 */
export interface GetAccessRequestIdentityMetricsV1401ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetAccessRequestIdentityMetricsV1401ResponseV1
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface GetAccessRequestIdentityMetricsV1429ResponseV1
 */
export interface GetAccessRequestIdentityMetricsV1429ResponseV1 {
    /**
     * A message describing the error
     * @type {any}
     * @memberof GetAccessRequestIdentityMetricsV1429ResponseV1
     */
    'message'?: any;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleoriginV1 = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleoriginV1 = typeof LocaleoriginV1[keyof typeof LocaleoriginV1];



/**
 * AccessRequestIdentityMetricsV1Api - axios parameter creator
 * @export
 */
export const AccessRequestIdentityMetricsV1ApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Use this API to return information access metrics.
         * @summary Return access request identity metrics
         * @param {string} identityId Manager\&#39;s identity ID.
         * @param {string} requestedObjectId Requested access item\&#39;s ID.
         * @param {GetAccessRequestIdentityMetricsV1TypeV1} type Requested access item\&#39;s type.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getAccessRequestIdentityMetricsV1: async (identityId: string, requestedObjectId: string, type: GetAccessRequestIdentityMetricsV1TypeV1, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'identityId' is not null or undefined
            assertParamExists('getAccessRequestIdentityMetricsV1', 'identityId', identityId)
            // verify required parameter 'requestedObjectId' is not null or undefined
            assertParamExists('getAccessRequestIdentityMetricsV1', 'requestedObjectId', requestedObjectId)
            // verify required parameter 'type' is not null or undefined
            assertParamExists('getAccessRequestIdentityMetricsV1', 'type', type)
            const localVarPath = `/access-request-identity-metrics/v1/{identityId}/requested-objects/{requestedObjectId}/type/{type}`
                .replace(`{${"identityId"}}`, encodeURIComponent(String(identityId)))
                .replace(`{${"requestedObjectId"}}`, encodeURIComponent(String(requestedObjectId)))
                .replace(`{${"type"}}`, encodeURIComponent(String(type)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * AccessRequestIdentityMetricsV1Api - functional programming interface
 * @export
 */
export const AccessRequestIdentityMetricsV1ApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = AccessRequestIdentityMetricsV1ApiAxiosParamCreator(configuration)
    return {
        /**
         * Use this API to return information access metrics.
         * @summary Return access request identity metrics
         * @param {string} identityId Manager\&#39;s identity ID.
         * @param {string} requestedObjectId Requested access item\&#39;s ID.
         * @param {GetAccessRequestIdentityMetricsV1TypeV1} type Requested access item\&#39;s type.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getAccessRequestIdentityMetricsV1(identityId: string, requestedObjectId: string, type: GetAccessRequestIdentityMetricsV1TypeV1, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getAccessRequestIdentityMetricsV1(identityId, requestedObjectId, type, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['AccessRequestIdentityMetricsV1Api.getAccessRequestIdentityMetricsV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * AccessRequestIdentityMetricsV1Api - factory interface
 * @export
 */
export const AccessRequestIdentityMetricsV1ApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = AccessRequestIdentityMetricsV1ApiFp(configuration)
    return {
        /**
         * Use this API to return information access metrics.
         * @summary Return access request identity metrics
         * @param {AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getAccessRequestIdentityMetricsV1(requestParameters: AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.getAccessRequestIdentityMetricsV1(requestParameters.identityId, requestParameters.requestedObjectId, requestParameters.type, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for getAccessRequestIdentityMetricsV1 operation in AccessRequestIdentityMetricsV1Api.
 * @export
 * @interface AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request
 */
export interface AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request {
    /**
     * Manager\&#39;s identity ID.
     * @type {string}
     * @memberof AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1
     */
    readonly identityId: string

    /**
     * Requested access item\&#39;s ID.
     * @type {string}
     * @memberof AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1
     */
    readonly requestedObjectId: string

    /**
     * Requested access item\&#39;s type.
     * @type {'ENTITLEMENT' | 'ROLE' | 'ACCESS_PROFILE'}
     * @memberof AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1
     */
    readonly type: GetAccessRequestIdentityMetricsV1TypeV1
}

/**
 * AccessRequestIdentityMetricsV1Api - object-oriented interface
 * @export
 * @class AccessRequestIdentityMetricsV1Api
 * @extends {BaseAPI}
 */
export class AccessRequestIdentityMetricsV1Api extends BaseAPI {
    /**
     * Use this API to return information access metrics.
     * @summary Return access request identity metrics
     * @param {AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof AccessRequestIdentityMetricsV1Api
     */
    public getAccessRequestIdentityMetricsV1(requestParameters: AccessRequestIdentityMetricsV1ApiGetAccessRequestIdentityMetricsV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return AccessRequestIdentityMetricsV1ApiFp(this.configuration).getAccessRequestIdentityMetricsV1(requestParameters.identityId, requestParameters.requestedObjectId, requestParameters.type, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}

/**
 * @export
 */
export const GetAccessRequestIdentityMetricsV1TypeV1 = {
    Entitlement: 'ENTITLEMENT',
    Role: 'ROLE',
    AccessProfile: 'ACCESS_PROFILE'
} as const;
export type GetAccessRequestIdentityMetricsV1TypeV1 = typeof GetAccessRequestIdentityMetricsV1TypeV1[keyof typeof GetAccessRequestIdentityMetricsV1TypeV1];


