- path: /password-org-config
  method: POST
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        import { Configuration, PasswordConfigurationBetaApi, PasswordOrgConfigBeta } from "sailpoint-api-client";
        const apiConfig = new Configuration();
        const passwordConfigurationBetaApi = new PasswordConfigurationBetaApi(apiConfig);

        const passwordOrgConfigBeta : PasswordOrgConfigBeta = {customInstructionsEnabled=true, digitTokenEnabled=true, digitTokenDurationMinutes=12, digitTokenLength=9}; // 

        try {
          const val = await passwordConfigurationBetaApi.createPasswordOrgConfig(passwordOrgConfigBeta);
          
          // Below is a request that includes all optional parameters 
          // const val = await passwordConfigurationBetaApi.createPasswordOrgConfig(passwordOrgConfigBeta);
          console.log('API called successfully. Returned data: ' + val.data);
          
        } catch (error) {
          console.error('Error occurred while calling API: ', error);
        }
- path: /password-org-config
  method: GET
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        import { Configuration, PasswordConfigurationBetaApi } from "sailpoint-api-client";
        const apiConfig = new Configuration();
        const passwordConfigurationBetaApi = new PasswordConfigurationBetaApi(apiConfig);


        try {
          const val = await passwordConfigurationBetaApi.getPasswordOrgConfig();
          
          // Below is a request that includes all optional parameters 
          // const val = await passwordConfigurationBetaApi.getPasswordOrgConfig();
          console.log('API called successfully. Returned data: ' + val.data);
          
        } catch (error) {
          console.error('Error occurred while calling API: ', error);
        }
- path: /password-org-config
  method: PUT
  xCodeSample:
    - lang: TypeScript
      label: SDK
      source: |
        import { Configuration, PasswordConfigurationBetaApi, PasswordOrgConfigBeta } from "sailpoint-api-client";
        const apiConfig = new Configuration();
        const passwordConfigurationBetaApi = new PasswordConfigurationBetaApi(apiConfig);

        const passwordOrgConfigBeta : PasswordOrgConfigBeta = {digitTokenEnabled=true, digitTokenDurationMinutes=12}; // 

        try {
          const val = await passwordConfigurationBetaApi.putPasswordOrgConfig(passwordOrgConfigBeta);
          
          // Below is a request that includes all optional parameters 
          // const val = await passwordConfigurationBetaApi.putPasswordOrgConfig(passwordOrgConfigBeta);
          console.log('API called successfully. Returned data: ' + val.data);
          
        } catch (error) {
          console.error('Error occurred while calling API: ', error);
        }
