/* tslint:disable */
/* eslint-disable */
/**
 * Identity Security Cloud API - Role Propagation
 * Use these APIs to interact with the Identity Security Cloud platform to achieve repeatable, automated processes with greater scalability. We encourage you to join the SailPoint Developer Community forum at https://developer.sailpoint.com/discuss to connect with other developers using our APIs.
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from './common';
import type { RequestArgs } from './base';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, BaseAPI, RequiredError, operationServerMap } from './base';

/**
 * 
 * @export
 * @interface ErrorMessageDto
 */
export interface ErrorMessageDto {
    /**
     * The locale for the message text, a BCP 47 language tag.
     * @type {string}
     * @memberof ErrorMessageDto
     */
    'locale'?: string | null;
    /**
     * 
     * @type {LocaleOrigin}
     * @memberof ErrorMessageDto
     */
    'localeOrigin'?: LocaleOrigin | null;
    /**
     * Actual text of the error message in the indicated locale.
     * @type {string}
     * @memberof ErrorMessageDto
     */
    'text'?: string;
}


/**
 * 
 * @export
 * @interface ErrorResponseDto
 */
export interface ErrorResponseDto {
    /**
     * Fine-grained error code providing more detail of the error.
     * @type {string}
     * @memberof ErrorResponseDto
     */
    'detailCode'?: string;
    /**
     * Unique tracking id for the error.
     * @type {string}
     * @memberof ErrorResponseDto
     */
    'trackingId'?: string;
    /**
     * Generic localized reason for error
     * @type {Array<ErrorMessageDto>}
     * @memberof ErrorResponseDto
     */
    'messages'?: Array<ErrorMessageDto>;
    /**
     * Plain-text descriptive reasons to provide additional detail to the text provided in the messages field
     * @type {Array<ErrorMessageDto>}
     * @memberof ErrorResponseDto
     */
    'causes'?: Array<ErrorMessageDto>;
}
/**
 * An indicator of how the locale was selected. *DEFAULT* means the locale is the system default. *REQUEST* means the locale was selected from the request context (i.e., best match based on the *Accept-Language* header). Additional values may be added in the future without notice.
 * @export
 * @enum {string}
 */

export const LocaleOrigin = {
    Default: 'DEFAULT',
    Request: 'REQUEST'
} as const;

export type LocaleOrigin = typeof LocaleOrigin[keyof typeof LocaleOrigin];


/**
 * Role Change Propagation Config Input
 * @export
 * @interface Rolepropagationconfiginput
 */
export interface Rolepropagationconfiginput {
    /**
     * Indicates if the Role Change Propagation process should be enabled for the tenant
     * @type {boolean}
     * @memberof Rolepropagationconfiginput
     */
    'enabled'?: boolean;
}
/**
 * Role Change Propagation Config Response
 * @export
 * @interface Rolepropagationconfigresponse
 */
export interface Rolepropagationconfigresponse {
    /**
     * Indicates if the Role Change Propagation process is enabled for the tenant
     * @type {boolean}
     * @memberof Rolepropagationconfigresponse
     */
    'enabled'?: boolean;
    /**
     * The time when Role Change Propagation Process was last enabled on the tenant
     * @type {string}
     * @memberof Rolepropagationconfigresponse
     */
    'enabledDate'?: string;
    /**
     * The time when Role Change Propagation Configuration was first created for the tenant
     * @type {string}
     * @memberof Rolepropagationconfigresponse
     */
    'createdDate'?: string;
    /**
     * The time when Role Change Propagation Config was updated on the tenant
     * @type {string}
     * @memberof Rolepropagationconfigresponse
     */
    'modifiedDate'?: string;
}
/**
 * Running Role Propagation Response
 * @export
 * @interface Rolepropagationongoingresponse
 */
export interface Rolepropagationongoingresponse {
    /**
     * Indicates if the role propagation process is currently running on the tenant
     * @type {boolean}
     * @memberof Rolepropagationongoingresponse
     */
    'isRunning'?: boolean;
    /**
     * 
     * @type {RolepropagationongoingresponseRolePropagationDetails}
     * @memberof Rolepropagationongoingresponse
     */
    'rolePropagationDetails'?: RolepropagationongoingresponseRolePropagationDetails;
}
/**
 * Details of the ongoing role propagation process
 * @export
 * @interface RolepropagationongoingresponseRolePropagationDetails
 */
export interface RolepropagationongoingresponseRolePropagationDetails {
    /**
     * Id of the Role Propagation process triggered.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'id'?: string;
    /**
     * Status of the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'status'?: RolepropagationongoingresponseRolePropagationDetailsStatusEnum;
    /**
     * Current execution stage of the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'executionStage'?: RolepropagationongoingresponseRolePropagationDetailsExecutionStageEnum;
    /**
     * Time when the Role Propagation process was launched.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'launched'?: string;
    /**
     * 
     * @type {RolepropagationstatusresponseLaunchedBy}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'launchedBy'?: RolepropagationstatusresponseLaunchedBy;
    /**
     * 
     * @type {RolepropagationstatusresponseTerminatedBy}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'terminatedBy'?: RolepropagationstatusresponseTerminatedBy;
    /**
     * Time when the Role Propagation process was completed.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'completed'?: string;
    /**
     * Reason for failure if the Role Propagation process failed.
     * @type {string}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'failureReason'?: string;
    /**
     * Indicates if the role refresh was skipped during the Role Propagation process.
     * @type {boolean}
     * @memberof RolepropagationongoingresponseRolePropagationDetails
     */
    'skipRoleRefresh'?: boolean;
}

export const RolepropagationongoingresponseRolePropagationDetailsStatusEnum = {
    Running: 'RUNNING',
    Completed: 'COMPLETED'
} as const;

export type RolepropagationongoingresponseRolePropagationDetailsStatusEnum = typeof RolepropagationongoingresponseRolePropagationDetailsStatusEnum[keyof typeof RolepropagationongoingresponseRolePropagationDetailsStatusEnum];
export const RolepropagationongoingresponseRolePropagationDetailsExecutionStageEnum = {
    Pending: 'PENDING',
    DataAggregationRunning: 'DATA_AGGREGATION_RUNNING',
    LaunchProvisioning: 'LAUNCH_PROVISIONING',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED',
    Terminated: 'TERMINATED'
} as const;

export type RolepropagationongoingresponseRolePropagationDetailsExecutionStageEnum = typeof RolepropagationongoingresponseRolePropagationDetailsExecutionStageEnum[keyof typeof RolepropagationongoingresponseRolePropagationDetailsExecutionStageEnum];

/**
 * Role Propagation Response
 * @export
 * @interface Rolepropagationresponse
 */
export interface Rolepropagationresponse {
    /**
     * Id of the Role Propagation process triggered.
     * @type {string}
     * @memberof Rolepropagationresponse
     */
    'rolePropagationId'?: string;
}
/**
 * Role Propagation Status Response
 * @export
 * @interface Rolepropagationstatusresponse
 */
export interface Rolepropagationstatusresponse {
    /**
     * Id of the Role Propagation process triggered.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'id'?: string;
    /**
     * Status of the Role Propagation process.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'status'?: RolepropagationstatusresponseStatusEnum;
    /**
     * Current execution stage of the Role Propagation process.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'executionStage'?: RolepropagationstatusresponseExecutionStageEnum;
    /**
     * Time when the Role Propagation process was launched.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'launched'?: string;
    /**
     * 
     * @type {RolepropagationstatusresponseLaunchedBy}
     * @memberof Rolepropagationstatusresponse
     */
    'launchedBy'?: RolepropagationstatusresponseLaunchedBy;
    /**
     * 
     * @type {RolepropagationstatusresponseTerminatedBy}
     * @memberof Rolepropagationstatusresponse
     */
    'terminatedBy'?: RolepropagationstatusresponseTerminatedBy;
    /**
     * Time when the Role Propagation process was completed.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'completed'?: string;
    /**
     * Reason for failure if the Role Propagation process failed.
     * @type {string}
     * @memberof Rolepropagationstatusresponse
     */
    'failureReason'?: string;
    /**
     * Indicates if the role refresh was skipped during the Role Propagation process.
     * @type {boolean}
     * @memberof Rolepropagationstatusresponse
     */
    'skipRoleRefresh'?: boolean;
}

export const RolepropagationstatusresponseStatusEnum = {
    Running: 'RUNNING',
    Completed: 'COMPLETED'
} as const;

export type RolepropagationstatusresponseStatusEnum = typeof RolepropagationstatusresponseStatusEnum[keyof typeof RolepropagationstatusresponseStatusEnum];
export const RolepropagationstatusresponseExecutionStageEnum = {
    Pending: 'PENDING',
    DataAggregationRunning: 'DATA_AGGREGATION_RUNNING',
    LaunchProvisioning: 'LAUNCH_PROVISIONING',
    Succeeded: 'SUCCEEDED',
    Failed: 'FAILED',
    Terminated: 'TERMINATED'
} as const;

export type RolepropagationstatusresponseExecutionStageEnum = typeof RolepropagationstatusresponseExecutionStageEnum[keyof typeof RolepropagationstatusresponseExecutionStageEnum];

/**
 * Identity who launched the Role Propagation process.
 * @export
 * @interface RolepropagationstatusresponseLaunchedBy
 */
export interface RolepropagationstatusresponseLaunchedBy {
    /**
     * DTO type of the identity who launched the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseLaunchedBy
     */
    'type'?: RolepropagationstatusresponseLaunchedByTypeEnum;
    /**
     * ID of the identity who launched the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseLaunchedBy
     */
    'id'?: string;
    /**
     * Name of the identity who launched the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseLaunchedBy
     */
    'name'?: string;
}

export const RolepropagationstatusresponseLaunchedByTypeEnum = {
    Identity: 'IDENTITY'
} as const;

export type RolepropagationstatusresponseLaunchedByTypeEnum = typeof RolepropagationstatusresponseLaunchedByTypeEnum[keyof typeof RolepropagationstatusresponseLaunchedByTypeEnum];

/**
 * Identity who terminated the Role Propagation process.
 * @export
 * @interface RolepropagationstatusresponseTerminatedBy
 */
export interface RolepropagationstatusresponseTerminatedBy {
    /**
     * DTO type of the Identity who terminated the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseTerminatedBy
     */
    'type'?: RolepropagationstatusresponseTerminatedByTypeEnum;
    /**
     * ID of the Identity who terminated the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseTerminatedBy
     */
    'id'?: string;
    /**
     * Name of the Identity who terminated the Role Propagation process.
     * @type {string}
     * @memberof RolepropagationstatusresponseTerminatedBy
     */
    'name'?: string;
}

export const RolepropagationstatusresponseTerminatedByTypeEnum = {
    Identity: 'IDENTITY'
} as const;

export type RolepropagationstatusresponseTerminatedByTypeEnum = typeof RolepropagationstatusresponseTerminatedByTypeEnum[keyof typeof RolepropagationstatusresponseTerminatedByTypeEnum];

/**
 * 
 * @export
 * @interface StartRolePropagationV1401Response
 */
export interface StartRolePropagationV1401Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof StartRolePropagationV1401Response
     */
    'error'?: any;
}
/**
 * 
 * @export
 * @interface StartRolePropagationV1429Response
 */
export interface StartRolePropagationV1429Response {
    /**
     * A message describing the error
     * @type {any}
     * @memberof StartRolePropagationV1429Response
     */
    'message'?: any;
}

/**
 * RolePropagationApi - axios parameter creator
 * @export
 */
export const RolePropagationApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * This endpoint terminates the ongoing role change propagation process for a tenant.
         * @summary Terminate Role Propagation process
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        cancelRolePropagationV1: async (xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation/v1/terminate`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This endpoint returns the information of ongoing role change propagation process for a tenant. It returns the information whether the role propagation process is currently running or not, If it is running it returns the details of the ongoing role propagation process. The execution stage of the role propagation process can be one of the following: - PENDING - The role propagation process is queued to be executed. - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data. - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities. - SUCCEEDED - The role propagation process has successfully completed. - FAILED - The role propagation process has failed. - TERMINATED - The role propagation process was externally terminated.
         * @summary Get ongoing Role Propagation process
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getOngoingRolePropagationV1: async (xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation/v1/is-running`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This endpoint fetches the Role Change Propagation Configuration for the tenant
         * @summary Get Role Change Propagation Configuration
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getRolePropagationConfigV1: async (xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation-config/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This endpoint returns the information of the specified role change propagation process. The execution stage of the role propagation process can be one of the following:     - PENDING - The role propagation process is queued to be executed.     - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data.     - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities.     - SUCCEEDED - The role propagation process has successfully completed.     - FAILED - The role propagation process has failed.     - TERMINATED - The role propagation process was externally terminated.
         * @summary Get status of Role-Propagation process
         * @param {string} rolePropagationId The ID of the role propagation process to retrieve the status for.
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getRolePropagationStatusV1: async (rolePropagationId: string, xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rolePropagationId' is not null or undefined
            assertParamExists('getRolePropagationStatusV1', 'rolePropagationId', rolePropagationId)
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation/v1/{rolePropagationId}/status`
                .replace(`{${"rolePropagationId"}}`, encodeURIComponent(String(rolePropagationId)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This endpoint enables or disables the Role Change Propagation Process for the tenant
         * @summary Update Role Change Propagation Configuration
         * @param {Rolepropagationconfiginput} rolepropagationconfiginput 
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        setRolePropagationConfigV1: async (rolepropagationconfiginput: Rolepropagationconfiginput, xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'rolepropagationconfiginput' is not null or undefined
            assertParamExists('setRolePropagationConfigV1', 'rolepropagationconfiginput', rolepropagationconfiginput)
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation-config/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'PUT', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(rolepropagationconfiginput, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
        /**
         * This endpoint initiates a role change propagation process for a tenant asynchronously.  If all preconditions are met, the request is accepted and a rolePropagationId is returned which  can be used to view the status. API throws 4xx if any of the following conditions are met - Role propagation feature is disabled  - There is an ongoing role propagation for the tenant - Role refresh needs to be kicked off as part of the role propagation (skipRoleRefresh=false) and there is an ongoing refresh for the tenant
         * @summary Initiate Role Propagation process
         * @param {boolean} [skipRoleRefresh] When true, the role refresh is not performed. Keeping it false is recommended.
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        startRolePropagationV1: async (skipRoleRefresh?: boolean, xSailPointExperimental?: string, axiosOptions: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            if (xSailPointExperimental === undefined) {
                xSailPointExperimental = 'true';
            }
            
            const localVarPath = `/role-propagation/v1`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...axiosOptions};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (skipRoleRefresh !== undefined) {
                localVarQueryParameter['skipRoleRefresh'] = skipRoleRefresh;
            }


    
            if (xSailPointExperimental != null) {
                localVarHeaderParameter['X-SailPoint-Experimental'] = String(xSailPointExperimental);
            }
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...axiosOptions.headers};

            return {
                url: toPathString(localVarUrlObj),
                axiosOptions: localVarRequestOptions,
            };
        },
    }
};

/**
 * RolePropagationApi - functional programming interface
 * @export
 */
export const RolePropagationApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = RolePropagationApiAxiosParamCreator(configuration)
    return {
        /**
         * This endpoint terminates the ongoing role change propagation process for a tenant.
         * @summary Terminate Role Propagation process
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async cancelRolePropagationV1(xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.cancelRolePropagationV1(xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.cancelRolePropagationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint returns the information of ongoing role change propagation process for a tenant. It returns the information whether the role propagation process is currently running or not, If it is running it returns the details of the ongoing role propagation process. The execution stage of the role propagation process can be one of the following: - PENDING - The role propagation process is queued to be executed. - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data. - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities. - SUCCEEDED - The role propagation process has successfully completed. - FAILED - The role propagation process has failed. - TERMINATED - The role propagation process was externally terminated.
         * @summary Get ongoing Role Propagation process
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getOngoingRolePropagationV1(xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rolepropagationongoingresponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getOngoingRolePropagationV1(xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.getOngoingRolePropagationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint fetches the Role Change Propagation Configuration for the tenant
         * @summary Get Role Change Propagation Configuration
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getRolePropagationConfigV1(xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rolepropagationconfigresponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRolePropagationConfigV1(xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.getRolePropagationConfigV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint returns the information of the specified role change propagation process. The execution stage of the role propagation process can be one of the following:     - PENDING - The role propagation process is queued to be executed.     - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data.     - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities.     - SUCCEEDED - The role propagation process has successfully completed.     - FAILED - The role propagation process has failed.     - TERMINATED - The role propagation process was externally terminated.
         * @summary Get status of Role-Propagation process
         * @param {string} rolePropagationId The ID of the role propagation process to retrieve the status for.
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async getRolePropagationStatusV1(rolePropagationId: string, xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rolepropagationstatusresponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getRolePropagationStatusV1(rolePropagationId, xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.getRolePropagationStatusV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint enables or disables the Role Change Propagation Process for the tenant
         * @summary Update Role Change Propagation Configuration
         * @param {Rolepropagationconfiginput} rolepropagationconfiginput 
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async setRolePropagationConfigV1(rolepropagationconfiginput: Rolepropagationconfiginput, xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rolepropagationconfigresponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.setRolePropagationConfigV1(rolepropagationconfiginput, xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.setRolePropagationConfigV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * This endpoint initiates a role change propagation process for a tenant asynchronously.  If all preconditions are met, the request is accepted and a rolePropagationId is returned which  can be used to view the status. API throws 4xx if any of the following conditions are met - Role propagation feature is disabled  - There is an ongoing role propagation for the tenant - Role refresh needs to be kicked off as part of the role propagation (skipRoleRefresh=false) and there is an ongoing refresh for the tenant
         * @summary Initiate Role Propagation process
         * @param {boolean} [skipRoleRefresh] When true, the role refresh is not performed. Keeping it false is recommended.
         * @param {string} [xSailPointExperimental] Use this header to enable this experimental API.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        async startRolePropagationV1(skipRoleRefresh?: boolean, xSailPointExperimental?: string, axiosOptions?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<Rolepropagationresponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.startRolePropagationV1(skipRoleRefresh, xSailPointExperimental, axiosOptions);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['RolePropagationApi.startRolePropagationV1']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * RolePropagationApi - factory interface
 * @export
 */
export const RolePropagationApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = RolePropagationApiFp(configuration)
    return {
        /**
         * This endpoint terminates the ongoing role change propagation process for a tenant.
         * @summary Terminate Role Propagation process
         * @param {RolePropagationApiCancelRolePropagationV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        cancelRolePropagationV1(requestParameters: RolePropagationApiCancelRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.cancelRolePropagationV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint returns the information of ongoing role change propagation process for a tenant. It returns the information whether the role propagation process is currently running or not, If it is running it returns the details of the ongoing role propagation process. The execution stage of the role propagation process can be one of the following: - PENDING - The role propagation process is queued to be executed. - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data. - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities. - SUCCEEDED - The role propagation process has successfully completed. - FAILED - The role propagation process has failed. - TERMINATED - The role propagation process was externally terminated.
         * @summary Get ongoing Role Propagation process
         * @param {RolePropagationApiGetOngoingRolePropagationV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getOngoingRolePropagationV1(requestParameters: RolePropagationApiGetOngoingRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Rolepropagationongoingresponse> {
            return localVarFp.getOngoingRolePropagationV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint fetches the Role Change Propagation Configuration for the tenant
         * @summary Get Role Change Propagation Configuration
         * @param {RolePropagationApiGetRolePropagationConfigV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getRolePropagationConfigV1(requestParameters: RolePropagationApiGetRolePropagationConfigV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Rolepropagationconfigresponse> {
            return localVarFp.getRolePropagationConfigV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint returns the information of the specified role change propagation process. The execution stage of the role propagation process can be one of the following:     - PENDING - The role propagation process is queued to be executed.     - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data.     - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities.     - SUCCEEDED - The role propagation process has successfully completed.     - FAILED - The role propagation process has failed.     - TERMINATED - The role propagation process was externally terminated.
         * @summary Get status of Role-Propagation process
         * @param {RolePropagationApiGetRolePropagationStatusV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        getRolePropagationStatusV1(requestParameters: RolePropagationApiGetRolePropagationStatusV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Rolepropagationstatusresponse> {
            return localVarFp.getRolePropagationStatusV1(requestParameters.rolePropagationId, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint enables or disables the Role Change Propagation Process for the tenant
         * @summary Update Role Change Propagation Configuration
         * @param {RolePropagationApiSetRolePropagationConfigV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        setRolePropagationConfigV1(requestParameters: RolePropagationApiSetRolePropagationConfigV1Request, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Rolepropagationconfigresponse> {
            return localVarFp.setRolePropagationConfigV1(requestParameters.rolepropagationconfiginput, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
        /**
         * This endpoint initiates a role change propagation process for a tenant asynchronously.  If all preconditions are met, the request is accepted and a rolePropagationId is returned which  can be used to view the status. API throws 4xx if any of the following conditions are met - Role propagation feature is disabled  - There is an ongoing role propagation for the tenant - Role refresh needs to be kicked off as part of the role propagation (skipRoleRefresh=false) and there is an ongoing refresh for the tenant
         * @summary Initiate Role Propagation process
         * @param {RolePropagationApiStartRolePropagationV1Request} requestParameters Request parameters.
         * @param {*} [axiosOptions] Override http request option.
         * @throws {RequiredError}
         */
        startRolePropagationV1(requestParameters: RolePropagationApiStartRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig): AxiosPromise<Rolepropagationresponse> {
            return localVarFp.startRolePropagationV1(requestParameters.skipRoleRefresh, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for cancelRolePropagationV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiCancelRolePropagationV1Request
 */
export interface RolePropagationApiCancelRolePropagationV1Request {
    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiCancelRolePropagationV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * Request parameters for getOngoingRolePropagationV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiGetOngoingRolePropagationV1Request
 */
export interface RolePropagationApiGetOngoingRolePropagationV1Request {
    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiGetOngoingRolePropagationV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * Request parameters for getRolePropagationConfigV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiGetRolePropagationConfigV1Request
 */
export interface RolePropagationApiGetRolePropagationConfigV1Request {
    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiGetRolePropagationConfigV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * Request parameters for getRolePropagationStatusV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiGetRolePropagationStatusV1Request
 */
export interface RolePropagationApiGetRolePropagationStatusV1Request {
    /**
     * The ID of the role propagation process to retrieve the status for.
     * @type {string}
     * @memberof RolePropagationApiGetRolePropagationStatusV1
     */
    readonly rolePropagationId: string

    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiGetRolePropagationStatusV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * Request parameters for setRolePropagationConfigV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiSetRolePropagationConfigV1Request
 */
export interface RolePropagationApiSetRolePropagationConfigV1Request {
    /**
     * 
     * @type {Rolepropagationconfiginput}
     * @memberof RolePropagationApiSetRolePropagationConfigV1
     */
    readonly rolepropagationconfiginput: Rolepropagationconfiginput

    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiSetRolePropagationConfigV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * Request parameters for startRolePropagationV1 operation in RolePropagationApi.
 * @export
 * @interface RolePropagationApiStartRolePropagationV1Request
 */
export interface RolePropagationApiStartRolePropagationV1Request {
    /**
     * When true, the role refresh is not performed. Keeping it false is recommended.
     * @type {boolean}
     * @memberof RolePropagationApiStartRolePropagationV1
     */
    readonly skipRoleRefresh?: boolean

    /**
     * Use this header to enable this experimental API.
     * @type {string}
     * @memberof RolePropagationApiStartRolePropagationV1
     */
    readonly xSailPointExperimental?: string
}

/**
 * RolePropagationApi - object-oriented interface
 * @export
 * @class RolePropagationApi
 * @extends {BaseAPI}
 */
export class RolePropagationApi extends BaseAPI {
    /**
     * This endpoint terminates the ongoing role change propagation process for a tenant.
     * @summary Terminate Role Propagation process
     * @param {RolePropagationApiCancelRolePropagationV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public cancelRolePropagationV1(requestParameters: RolePropagationApiCancelRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).cancelRolePropagationV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint returns the information of ongoing role change propagation process for a tenant. It returns the information whether the role propagation process is currently running or not, If it is running it returns the details of the ongoing role propagation process. The execution stage of the role propagation process can be one of the following: - PENDING - The role propagation process is queued to be executed. - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data. - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities. - SUCCEEDED - The role propagation process has successfully completed. - FAILED - The role propagation process has failed. - TERMINATED - The role propagation process was externally terminated.
     * @summary Get ongoing Role Propagation process
     * @param {RolePropagationApiGetOngoingRolePropagationV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public getOngoingRolePropagationV1(requestParameters: RolePropagationApiGetOngoingRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).getOngoingRolePropagationV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint fetches the Role Change Propagation Configuration for the tenant
     * @summary Get Role Change Propagation Configuration
     * @param {RolePropagationApiGetRolePropagationConfigV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public getRolePropagationConfigV1(requestParameters: RolePropagationApiGetRolePropagationConfigV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).getRolePropagationConfigV1(requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint returns the information of the specified role change propagation process. The execution stage of the role propagation process can be one of the following:     - PENDING - The role propagation process is queued to be executed.     - DATA_AGGREGATION_RUNNING - The role propagation process is currently aggregating data.     - LAUNCH_PROVISIONING - The role propagation process has started to provision the access to the identities.     - SUCCEEDED - The role propagation process has successfully completed.     - FAILED - The role propagation process has failed.     - TERMINATED - The role propagation process was externally terminated.
     * @summary Get status of Role-Propagation process
     * @param {RolePropagationApiGetRolePropagationStatusV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public getRolePropagationStatusV1(requestParameters: RolePropagationApiGetRolePropagationStatusV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).getRolePropagationStatusV1(requestParameters.rolePropagationId, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint enables or disables the Role Change Propagation Process for the tenant
     * @summary Update Role Change Propagation Configuration
     * @param {RolePropagationApiSetRolePropagationConfigV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public setRolePropagationConfigV1(requestParameters: RolePropagationApiSetRolePropagationConfigV1Request, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).setRolePropagationConfigV1(requestParameters.rolepropagationconfiginput, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }

    /**
     * This endpoint initiates a role change propagation process for a tenant asynchronously.  If all preconditions are met, the request is accepted and a rolePropagationId is returned which  can be used to view the status. API throws 4xx if any of the following conditions are met - Role propagation feature is disabled  - There is an ongoing role propagation for the tenant - Role refresh needs to be kicked off as part of the role propagation (skipRoleRefresh=false) and there is an ongoing refresh for the tenant
     * @summary Initiate Role Propagation process
     * @param {RolePropagationApiStartRolePropagationV1Request} requestParameters Request parameters.
     * @param {*} [axiosOptions] Override http request option.
     * @throws {RequiredError}
     * @memberof RolePropagationApi
     */
    public startRolePropagationV1(requestParameters: RolePropagationApiStartRolePropagationV1Request = {}, axiosOptions?: RawAxiosRequestConfig) {
        return RolePropagationApiFp(this.configuration).startRolePropagationV1(requestParameters.skipRoleRefresh, requestParameters.xSailPointExperimental, axiosOptions).then((request) => request(this.axios, this.basePath));
    }
}



