name: "Build TypeScript SDK"
description: "Build all API versions of the TypeScript SDK from OpenAPI specs"

inputs:
  api-specs-path:
    description: "Path to the checked-out api-specs repository"
    required: false
    default: "api-specs"
  skip-tests:
    description: "Skip running tests after building"
    required: false
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version: "24"

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: "temurin"
        java-version: "17"

    - name: Download OpenAPI Generator
      shell: bash
      run: |
        wget -q https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.12.0/openapi-generator-cli-7.12.0.jar -O openapi-generator-cli.jar

    - name: Build V3 SDK
      shell: bash
      run: |
        rm -rf ./sdk-output/v3
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v3.yaml \
          -g typescript-axios -o sdk-output/v3 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v3-config.yaml

    - name: Build Beta SDK
      shell: bash
      run: |
        rm -rf ./sdk-output/beta
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.beta.yaml \
          -g typescript-axios -o sdk-output/beta \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/beta-config.yaml \
          --api-name-suffix BetaApi --model-name-suffix Beta

    - name: Build V2024 SDK
      shell: bash
      run: |
        rm -rf ./sdk-output/v2024
        node sdk-resources/prescript.js ${{ inputs.api-specs-path }}/idn/v2024/paths
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2024.yaml \
          -g typescript-axios -o sdk-output/v2024 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2024-config.yaml \
          --api-name-suffix V2024Api --model-name-suffix V2024

    - name: Build V2025 SDK
      shell: bash
      run: |
        rm -rf ./sdk-output/v2025
        node sdk-resources/prescript.js ${{ inputs.api-specs-path }}/idn/v2025/paths
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2025.yaml \
          -g typescript-axios -o sdk-output/v2025 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2025-config.yaml \
          --api-name-suffix V2025Api --model-name-suffix V2025

    - name: Build V2026 SDK
      shell: bash
      run: |
        rm -rf ./sdk-output/v2026
        node sdk-resources/prescript.js ${{ inputs.api-specs-path }}/idn/v2026/paths
        java -jar openapi-generator-cli.jar generate \
          -i ${{ inputs.api-specs-path }}/idn/sailpoint-api.v2026.yaml \
          -g typescript-axios -o sdk-output/v2026 \
          --global-property skipFormModel=false,apiDocs=true,modelDocs=true \
          --config sdk-resources/v2026-config.yaml \
          --api-name-suffix V2026Api --model-name-suffix V2026

    - name: Build and Test
      shell: bash
      run: |
        cd sdk-output
        npm install
        npm run build
        if [ "${{ inputs.skip-tests }}" != "true" ]; then
          npm run test
        fi
