name: "Build Typescript SDK"

env:
  SAIL_CLIENT_ID: ${{ secrets.SDK_TEST_TENANT_CLIENT_ID }}
  SAIL_CLIENT_SECRET: ${{ secrets.SDK_TEST_TENANT_CLIENT_SECRET }}
  SAIL_BASE_URL: ${{ secrets.SDK_TEST_TENANT_BASE_URL }}

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_typescript_sdk:
    name: Build typescript SDK
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.ref }}

      - name: Checkout API Specs Repo
        uses: actions/checkout@v3
        with:
          repository: sailpoint-oss/api-specs
          path: api-specs
          ref: main

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Download OpenAPI Generator
        run: |
            wget https://repo1.maven.org/maven2/org/openapitools/openapi-generator-cli/7.11.0/openapi-generator-cli-7.11.0.jar -O openapi-generator-cli.jar
  
      - name: Build V3 SDK
        id: buildV3
        run: |
          java -jar openapi-generator-cli.jar generate -i api-specs/idn/sailpoint-api.v3.yaml -g typescript-axios -o sdk-output/v3 --global-property skipFormModel=false --config sdk-resources/v3-config.yaml
      
      - name: Build Beta SDK
        id: buildBeta
        if: steps.buildV3.outcome == 'success'
        run: |
          java -jar openapi-generator-cli.jar generate -i api-specs/idn/sailpoint-api.beta.yaml -g typescript-axios -o sdk-output/beta --global-property skipFormModel=false --config sdk-resources/beta-config.yaml --api-name-suffix BetaApi --model-name-suffix Beta

      - name: Build V2024 SDK
        id: buildV2024
        if: steps.buildBeta.outcome == 'success'
        run: |
          node sdk-resources/prescript.js api-specs/idn/v2024/paths
          java -jar openapi-generator-cli.jar generate -i api-specs/idn/sailpoint-api.v2024.yaml -g typescript-axios -o sdk-output/v2024 --global-property skipFormModel=false --config sdk-resources/v2024-config.yaml --api-name-suffix V2024Api --model-name-suffix V2024


      - name: Run npm install and build Typescript SDK
        id: buildSDK
        if: steps.buildV2024.outcome == 'success'
        run: |
          cd sdk-output
          npm install
          npm run build
          npm run test
